WIP: Change diff renamed files
extrawurst/gitui pull request #1040
Opened 2021-12-12 03:47 UTC by Mifom

This Pull Request closes #1038.

It changes the following:
- Add status change on rename
- Change diff title to represent rename
- Change diff to show only rewrites on rename

I followed the checklist:
- [ ] I added unittests
- [X] I ran `make check` without errors
- [X] I tested the overall application
- [X] I added an appropriate item to the changelog

2021-12-12 09:03 UTC, extrawurst commented
@Mifom Thanks for looking into this. I played a bit around with you branch. did not check the code yet but two observations jump out:

a) we still do not detect renames against the workdir, this should be easy to add:
<img width="393" alt="Screenshot 2021-12-12 at 09 57 20" src="https://user-images.githubusercontent.com/776816/145706360-42b1af59-04ca-4f60-a9d2-1b42ad2401e5.png">

b) and then there is an issue staging hunks in the renamed&changed file:
![Screenflick Movie 26](https://user-images.githubusercontent.com/776816/145706385-ef75e553-3fce-4d0a-b584-4b3405ac1949.gif)

b) current hunk staging code is a bit wonky, so don't worry If thats the reason, then this might be better done in a separate PR

2021-12-12 09:59 UTC, extrawurst requested changes
lets add a dedicated unittest into asyncgit for the changed diff mechanic please

2021-12-12 09:59 UTC, extrawurst commented on CHANGELOG.md
> +- Correct diff of renamed files [[@Mifom](https://github.com/Mifom)] ([#1035](https://github.com/extrawurst/gitui/issues/1038))
1035 or 1038?

2021-12-12 09:59 UTC, extrawurst commented on src/tabs/status.rs
> +		// FIXME: replace with type
I am using `//TODO` for these, lets keep this consistent

2021-12-13 07:30 UTC, Mifom commented on CHANGELOG.md
> +- Correct diff of renamed files [[@Mifom](https://github.com/Mifom)] ([#1035](https://github.com/extrawurst/gitui/issues/1038))
Fixed by https://github.com/extrawurst/gitui/pull/1040/commits/f487a6e7bab1e8e1aec8d4e7d2357200efb314e7

2021-12-13 07:30 UTC, Mifom commented on src/tabs/status.rs
> +		// FIXME: replace with type
Fixed by https://github.com/extrawurst/gitui/pull/1040/commits/f487a6e7bab1e8e1aec8d4e7d2357200efb314e7

2021-12-13 07:37 UTC, Mifom commented
I'll mark it ready when I deal with hunks

2021-12-17 14:21 UTC, Mifom commented
For now hunks mostly done. But there are 2 issues:

1) Because destination file is untracked, diff in workdir is shown only for source file: 
![Screenshot from 2021-12-17 16-58-49](https://user-images.githubusercontent.com/23462908/146557512-02cc5193-d1e9-4ffb-9d36-7f6eb161c8e0.png)
git currently works the same way. Is this ok?

2) In staged renamed file is only one hunk - the whole file, so changes cannot be unstaged without unstaging full file:
![Screenshot from 2021-12-17 17-18-37](https://user-images.githubusercontent.com/23462908/146558235-d37fffa5-0170-47d6-b717-caaada3d6e5a.png)

2021-12-17 22:39 UTC, extrawurst commented
> is this issue need to be fixed in this PR? Currently it's not supported by git2 and libgit2.

i guess then not :)
But then we should just go for regular file-level stagin/upstaging when enter is used on a hunk in a renamed file I stead of creating an error

2021-12-17 22:40 UTC, extrawurst commented
Then this is ready ?

2021-12-17 22:58 UTC, Mifom commented
> Then this is ready ?

Yes

2021-12-17 23:00 UTC, Mifom commented
> > is this issue need to be fixed in this PR? Currently it's not supported by git2 and libgit2.
> 
> i guess then not :)
> But then we should just go for regular file-level stagin/upstaging when enter is used on a hunk in a renamed file I stead of creating an error

If I understand correctly this is how it works now

2021-12-21 16:43 UTC, extrawurst commented
@Mifom so functionality wise this looks awesome to me. but I am not sure what I am missing, cause I cannot reproduce the single-hunk-issue:
![Screenflick Movie 27](https://user-images.githubusercontent.com/776816/146966632-5f2f022b-8844-4016-a6d6-661ad9afe27e.gif)

looks pretty good to me, with the only glitch that removing a hunk removes the rename-part of the change aswell. but I guess thats a mini thing we can followup later with. especially cause its a philosophical decision of what should take precendence I guess :)

what do you think?

2021-12-21 17:11 UTC, extrawurst requested changes
just a few minor things left and a proper test for the rename case

2021-12-21 17:11 UTC, extrawurst commented on asyncgit/src/sync/diff.rs
> +	diff.find_similar(Some(
I think we should be able to get the same result by tweaking the diff options we pass in above

2021-12-21 17:11 UTC, extrawurst commented on asyncgit/src/sync/diff.rs
> +		let diff = get_diff(
is there also a test for the rename case?

2021-12-21 17:11 UTC, extrawurst commented on asyncgit/src/sync/status.rs
> +			status_entry // TODO: chain both Some(...) values
what about the TODO?

2021-12-21 17:11 UTC, extrawurst commented on asyncgit/src/sync/status.rs
> +	fn test_rename_file() -> Result<()> {
not sure I understand this test: its not testing anything from this lib but just git2-rs, right?

we need a rename test for our diffing/status functions

2021-12-21 17:11 UTC, extrawurst commented on src/tabs/status.rs
> +		// TODO: replace with type
lets do this

2021-12-21 17:19 UTC, extrawurst commented
I found another issue left:

![Screenflick Movie 28](https://user-images.githubusercontent.com/776816/146971755-f8d7ae8a-3602-428c-84a0-2264312d2089.gif)

So discarding a renamed file item (now only a single entry in the status list) should discard fully, old-path and new-path. please also add a test for this case.

2021-12-22 17:57 UTC, Mifom commented on asyncgit/src/sync/status.rs
> +			status_entry // TODO: chain both Some(...) values
I've done that
https://github.com/extrawurst/gitui/pull/1040/commits/126140de30d84c3e4e55716b3bccd05365e0999f

2021-12-22 17:57 UTC, Mifom commented on asyncgit/src/sync/status.rs
> +	fn test_rename_file() -> Result<()> {
Thanks for comment!
I fixed this
https://github.com/extrawurst/gitui/pull/1040/commits/7e45afda8bc8ee48d754fdc9f4dc39599c075047

2021-12-22 17:58 UTC, Mifom commented on src/tabs/status.rs
> +		// TODO: replace with type
Added DiffData
https://github.com/extrawurst/gitui/pull/1040/commits/28ac5addb76ff11695dffe7bb0952f69f36fbaca

2021-12-22 18:00 UTC, Mifom commented on asyncgit/src/sync/diff.rs
> +		let diff = get_diff(
Not sure that it test it, but git_diff now compare two files: old and new.

2021-12-22 18:01 UTC, Mifom commented on asyncgit/src/sync/diff.rs
> +	diff.find_similar(Some(
Sorry, but don't understand this comment.

2021-12-23 21:48 UTC, extrawurst commented on asyncgit/src/sync/diff.rs
> +		let diff = get_diff(
well I don't see that you added one, so we still need one for that case

2021-12-23 21:57 UTC, extrawurst commented
@Mifom let me know when I should review it again

2021-12-23 22:04 UTC, extrawurst commented on asyncgit/src/sync/diff.rs
> +	diff.find_similar(Some(
all good

2022-01-05 21:59 UTC, extrawurst commented
@Mifom how can I help you get this over the finish line?

2022-01-06 06:36 UTC, Mifom commented
@extrawurst I just need some time. I think I'll do it before the end of the week.

2022-01-09 15:55 UTC, extrawurst commented
@Mifom thanks for your continued effort, let me know when you think its ready

2022-01-17 14:13 UTC, extrawurst commented
@Mifom ping. feel free to join the discord if you need some feedback somewhere

2022-01-21 21:06 UTC, extrawurst commented
here is an issue when you want to discard a hunk in a renamed file:
<img width="850" alt="Screenshot 2022-01-21 at 22 04 32" src="https://user-images.githubusercontent.com/776816/150599954-73988e6d-deb2-40ce-a57f-585eac0627bf.png">

this will error-close with: 
```
Error: `hunk not found`
```

2022-01-21 21:09 UTC, extrawurst commented
here is an issue with line-staging:
<img width="848" alt="Screenshot 2022-01-21 at 22 07 16" src="https://user-images.githubusercontent.com/776816/150600258-217762fa-8d99-4d84-842b-2ee01413aa2a.png">

leads to:
<img width="850" alt="Screenshot 2022-01-21 at 22 07 54" src="https://user-images.githubusercontent.com/776816/150600315-fcc51d5b-3748-46f0-93fd-fca4917ff935.png">

as with above hunk error we can workaround this (if we don't wanna fix it now) by not allowing line based staging on renamed entries.

2022-01-21 21:22 UTC, extrawurst commented
when there is a rename involving a directory change then folder based staging does not work in a single step:

https://user-images.githubusercontent.com/776816/150601785-6e129f43-c05e-4057-9083-86bcf6d68998.mp4

2022-02-09 20:34 UTC, Mifom commented
The list of remaining changes:
 - [ ] test for rename file
 - [ ] test for discarding file
 - [ ] error with discarding hunk
 - [ ] error with line staging
 - [ ] issue with renaming directory

2022-04-01 12:31 UTC, Mifom commented on asyncgit/src/sync/diff.rs
> +		let diff = get_diff(
Test added at https://github.com/extrawurst/gitui/pull/1040/commits/1a199254edaaf3d3d1c4d801208bbcbae3aa9ea2

2022-04-01 12:37 UTC, Mifom commented
@extrawurst sorry for this long period without work on this PR.

There are no good way for discarding hunks in renamed files at the moment, so this was disabled.

About line staging: it works at least for the changes i made. Maybe there are cases where it will not work, so i'll check that.

About renamed folder staging: at the moment when user mark folder as staged it passes to staging on the side of git2, so we haven't control this. That's should be reimplemented in app side to accurately remove them and not only add new files.

2022-04-08 14:51 UTC, extrawurst commented
@Mifom can you bring the branch up to date with master, so it could in theory be merged?

2022-04-11 20:30 UTC, Mifom commented
> @Mifom can you bring the branch up to date with master, so it could in theory be merged?

Now it's up to date

2022-04-18 07:00 UTC, Mifom commented
@extrawurst the branch is now up to date
In the comment above I explain status of all issues with this PR. If you have ideas how to surpass them I can implement them or we can open new issue for them where they will be resolved.

2022-04-24 17:25 UTC, merged

2022-04-24 17:26 UTC, extrawurst commented
Thanks for sticking with this! 🥳

2022-04-24 20:16 UTC, extrawurst commented
I think I have to revert this. after the merge no `return` on any file in the file list works anymore to stage the whole file

2022-04-24 20:30 UTC, extrawurst commented
ok damn I don't get the changes made to `index_add_remove` now that I try to debug this. you seem to `sync::reset_stage` anything that was just staged in the same function. sorry I did not catch this before the merge. I will revert the change. feel free to reopen the PR

2022-04-24 20:38 UTC, extrawurst commented
@Mifom let me know if you need help figuring this out.