Add keybind to checkout commit in log view
extrawurst/gitui pull request #1055
Opened 2021-12-26 16:02 UTC by Omnikar

This Pull Request fixes/closes #983.

It changes the following:
- Adds `Shift-S` keybind to checkout the selected commit in the log view.

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

I think it'd be better if I could add a confirmation before detaching HEAD, similar to the one used for branch deletion and such, but I'm not sure how to.

2021-12-26 16:03 UTC, Omnikar commented on src/components/commitlist.rs
> +			};
Rustfmt decided to behave rather strangely here.

2021-12-27 13:05 UTC, extrawurst commented on src/components/commitlist.rs
> +			};
lgtm

2021-12-27 16:11 UTC, extrawurst requested changes

2021-12-27 16:11 UTC, extrawurst commented on src/components/commitlist.rs
> +					self.selected_entry().map(|entry| entry.id)
lets put this into a `self.checkout`

2021-12-27 16:11 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +		if let Err(e) = repo.checkout_head(Some(
there is a bunch of code duplication with `checkout_remote_branch` and `checkout_branch` - can reuse something?

2021-12-27 16:11 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +pub fn checkout_commit(
we need unittest(s) for `checkout_commit`

2021-12-27 18:11 UTC, Omnikar commented on asyncgit/src/sync/branch/mod.rs
> +pub fn checkout_commit(
Where should I put it?

2021-12-27 18:18 UTC, Omnikar commented
How do I get the keybind to appear in this bar at the bottom?
<img width="971" alt="image" src="https://user-images.githubusercontent.com/79615262/147497465-94223df2-f43e-4ce6-8f13-e7ead0e8c456.png">

2021-12-27 18:27 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +pub fn checkout_commit(
check the bottom of the file, there should be a few examples of tests for the other functions. use `cargo t --workspace` to run all tests and once ready run `make check` to validate what will be run on the CI

2021-12-27 18:29 UTC, extrawurst commented
> How do I get the keybind to appear in this bar at the bottom?

checkout the `commands` fn next to `events` to see how components add their commands

2022-01-09 15:18 UTC, extrawurst commented
@Omnikar feel free to reach out on our discord aswell

2022-01-21 21:28 UTC, extrawurst commented
@Omnikar are you planning to follow this up?

2022-01-21 23:05 UTC, Omnikar commented on asyncgit/src/sync/branch/mod.rs
> +		if let Err(e) = repo.checkout_head(Some(
I'm not sure exactly what I could extract, what do you suggest?

2022-01-30 23:52 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +pub fn checkout_commit(
Ping?

2022-09-10 20:47 UTC, closed without merging

2023-01-02 16:32 UTC, fralcow commented
Hey @Omnikar, I'm willing to pick this issue up. I see you left a couple of comments to the original author regarding unit tests and code reuse, should I pick up their branch and fix this stuff, or would you suggest writing the whole thing from scratch?

2023-01-04 20:46 UTC, fralcow commented
Hey @extrawurst , I'm willing to pick this issue up. I see you left a couple of comments to the original author regarding unit tests and code reuse, should I pick up their branch and fix this stuff, or would you suggest rewriting the whole thing from scratch?