Add word motions to text input
extrawurst/gitui pull request #1256
Opened 2022-07-13 23:59 UTC by Rodrigodd

It changes the following:
- Add common word motions to the text input component, more precisely `Ctrl-Left`, `Ctrl-Right`, `Ctrl-Backspace`/`Ctrl-W` and `Ctrl-Delete`. A word is being defined as a continuous sequence of alphanumeric characters.

I followed the checklist:
- [x] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

2022-08-17 16:28 UTC, extrawurst commented
this does not work on macos

2022-08-17 18:17 UTC, Rodrigodd commented
I have tested this on Windows and Linux (WSL). Unfortunately I don't have access to a macOS to test this. Can you tell me how exactly this is not working? The only platform dependent code I think might not be working is the `ctrl` modifier check, but this seems to be equivalent to the others in the codebase.

2022-09-02 07:31 UTC, extrawurst commented
can you please record how this should look like?

2022-09-02 17:49 UTC, Rodrigodd commented
@extrawurst I recorded it inside visual studio code for the keystrokes overlay. I notice that `Ctrl-Delete` don't work in vscode integrated terminal, but it does work in Windows Terminal.

https://user-images.githubusercontent.com/51273772/188209077-e6a13fdf-4f86-493b-a7eb-7cef66daa2d6.mp4

2022-09-02 17:59 UTC, extrawurst commented
it breaks on unicode text with multibyte content, try some emojis. it will run into some endless loop

2022-09-02 18:52 UTC, Rodrigodd commented
@extrawurst the infinite loop is fixed.

2022-09-03 08:31 UTC, extrawurst commented on src/components/textinput.rs
> +					KeyCode::Backspace | KeyCode::Char('w')
I am on the fence about the special case of `ctrl+w`. I am probably going to remove it for now. its hard to customize this way and I am not aware this being some standard

2022-09-03 11:50 UTC, extrawurst commented
also the changelog entry is still missing

2022-09-03 12:45 UTC, Rodrigodd commented on src/components/textinput.rs
> +					KeyCode::Backspace | KeyCode::Char('w')
As far as I know, Ctrl-W is the standart shortcut for "delete word" in a linux terminal (Ctrl-Delete don't work).
Because gitui is a terminal app, I tought this shortcut would be pertinent.
Vim, for example, has the same shortcut (it is where I learned about it).

2022-09-04 17:35 UTC, extrawurst commented on CHANGELOG.md
> +* word motions to text input ([#1256](https://github.com/extrawurst/gitui/issues/1256))
see the format of other contributions please - your handle is missing

2022-09-04 17:36 UTC, extrawurst requested changes
not much left to do. could you record a nice gif we can put in the changelog of the new functionality?

2022-09-04 18:42 UTC, Rodrigodd commented
> could you record a nice gif we can put in the changelog of the new functionality?

I don't have a easy recording workflow setup.

2022-09-08 06:50 UTC, merged

2022-09-08 06:50 UTC, extrawurst commented
Thanks for implementing this!