Allow copying multiple commits
extrawurst/gitui pull request #1288
Opened 2022-08-19 11:50 UTC by remique

This Pull Request fixes/closes #1244.

It changes the following:
- allows to copy multiple commits by marking them 

As of now, the functionality is as follows:
- No commits marked: copies selected line with short commit id
- One commit marked: copies long commit id
- More than one commit marked **consecutively**: copies `c1^..c8` 
- More than one commit marked **randomly**: copies `c1 c2 c4 c5 c8`

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

2022-08-22 10:06 UTC, remique commented
I have noticed that sometimes the app crashes after I yank the commits. I reckon that it is caused by sorting the indexes and I am looking into it.

2022-08-22 10:54 UTC, remique commented
Seems to be working now. I'm not sure if it is the greatest design, but works and does not crash.

2022-08-23 08:14 UTC, extrawurst commented
You seem to be saving indices. Did you check if that works still in big repos with the log being loaded in batches?

2022-08-23 12:22 UTC, remique commented
I'm only saving indices that have been marked. I tested it with [25k commit](https://github.com/sqlite/sqlite) repo and it works fine.

2022-08-26 06:17 UTC, extrawurst commented
can you make the required addition to the changelog?

2022-08-26 08:12 UTC, remique commented
Done!

2022-09-02 07:26 UTC, extrawurst commented on src/components/commitlist.rs
> +	marked_indexes: Vec<usize>,
please reuse `marked` here. feel free to make it a `Vec<(CommitId,usize)>` for example

2022-09-18 13:03 UTC, extrawurst commented on src/components/commitlist.rs
> +	marked_indexes: Vec<usize>,
@remique are you still on this?

2022-09-18 13:04 UTC, extrawurst commented
putting in draft until the required changes are made

2022-09-18 22:07 UTC, remique commented
Hey, I updated the changes and everything seems to be working fine on a big repo. I also ran `make check` locally with no errors. Failed build seems to be a clippy bug though? 

```
error[E0277]: expected a `FnOnce<()>` closure, found `std::string::String`
   --> src/components/commitlist.rs:195:20
    |
195 |                         .map_or_else(String::new(), |le| {
    |                          ----------- ^^^^^^^^^^^^^ expected an `FnOnce<()>` closure, found `std::string::String`
    |                          |
    |                          required by a bound introduced by this call
    |
    = help: the trait `FnOnce<()>` is not implemented for `std::string::String`
    = note: wrap the `std::string::String` in a closure with no arguments: `|| { /* code */ }`
```

2022-09-19 07:36 UTC, extrawurst commented on src/components/commitlist.rs
> +						|| String::from(""),
This is different code than the one you posted from your clippy warning.
the proper way to write this is: `map_or_else(String::new, ...`

2022-09-19 07:37 UTC, extrawurst requested changes
fix clippy nightly. see inline comment

2022-09-19 08:42 UTC, remique commented on src/components/commitlist.rs
> +						|| String::from(""),
Ah, was using `String::new()` and got an error. This always confuses me. Anyway, fixed that.

2022-09-19 08:54 UTC, merged

2022-09-19 08:54 UTC, extrawurst commented
Thank you ❤️