fix: returns 0 exit code on error
extrawurst/gitui pull request #1322
Opened 2022-09-10 12:24 UTC by snapdgn

This Pull Request fixes/closes #1315.

It changes the following:
- changes exit code to 1, while initializing gitui in a bare git repo (let me know if the exit code needs to be something else)

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

2022-09-11 08:39 UTC, extrawurst commented on src/main.rs
> +		process::exit(1);
Did you check if there other places that should return non zero?

2022-09-11 15:48 UTC, snapdgn commented on src/main.rs
> +		process::exit(1);
If you mean, checking at all potential places for all kinds of errors which should've returned a non-zero exit code. Sorry, I haven't. Will do :)

2022-09-13 07:54 UTC, SimonAdameit requested changes

2022-09-13 07:54 UTC, SimonAdameit commented on src/main.rs
> +		process::exit(1);
Thanks for tackling this! Wouldn't it be more ideomatic to use `return Err(..)` or `bail!(...)` here, as `main` returns a `Result`? I think an error should get turned into exit code `1` automatically.

2022-09-14 05:29 UTC, snapdgn commented on src/main.rs
> +		process::exit(1);
hey, thanks a lot for the review. I completely agree with you, will update this accordingly. Also, please do let me know, if there are any other places i could potentially look into, would be very grateful. Thanks!

2022-09-18 12:54 UTC, merged

2022-09-18 12:54 UTC, extrawurst commented
Thanks!