Refactor and shorten component creation
extrawurst/gitui pull request #1370
Opened 2022-10-03 10:25 UTC by alexmaco

It changes the following:
- adds one more usage of command_pump
- groups common items for components initialization in an Environment to reduce some repetition

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

2022-10-20 14:29 UTC, extrawurst commented
I like the idea. I would like to move forward with this. please rebase again and resolve the merge conflicts!

2023-10-14 17:29 UTC, alexmaco commented
@extrawurst perhaps another look at this?

2024-01-08 17:35 UTC, extrawurst commented on src/components/changes.rs
>  	#[allow(clippy::too_many_arguments)]
is this fixed by the change? can it be removed?

2024-01-08 17:36 UTC, extrawurst commented on src/components/commit.rs
> +	pub fn new(env: &crate::app::Environment) -> Self {
so far the other places import this instead of fully-qualifying. lets stay consistent

2024-01-08 17:43 UTC, extrawurst commented on src/app.rs
> +impl Default for Environment {
does it need to be the `Default` trait though? lets make it explicit and just make it a static fn `new_test_env`

2024-01-08 17:43 UTC, extrawurst commented on src/app.rs
> +			options: Default::default(),
same for `Options::default`

2024-01-08 17:44 UTC, extrawurst commented on src/options.rs
> +impl Default for Options {
see above

2024-01-08 17:44 UTC, extrawurst requested changes
obviously just nitpick. good work!

2024-02-12 10:57 UTC, extrawurst commented
@alexmaco are you still on this?

2024-02-12 11:15 UTC, extrawurst commented
made these cleanups myself now and will merge as part of #2043

2024-02-12 11:15 UTC, closed without merging