Add notification when correctly copying hash commit
extrawurst/gitui pull request #1376
Opened 2022-10-04 05:27 UTC by SergioRibera

This Pull Request fixes/closes #1160.

It changes the following:
- When copying the hash of a commit, it displays a confirmation dialog if it has been copied correctly

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

2022-10-06 09:50 UTC, alexmaco commented
I also ran into these usability issues with copying.

Maybe it would be useful to display the text that was copied in the notification?

Additionally, copying might fail (e.g. if both xclip and xsel are missing or if gitui is being run via ssh). The notification shouldn't report success without checking the result of the copy operation. Maybe a good place to catch that error is at the call site of `copy_commit_hash` in `commitlist.rs`?

2022-10-08 06:13 UTC, SergioRibera commented
> I also ran into these usability issues with copying.
> 
> Maybe it would be useful to display the text that was copied in the notification?
> 
> Additionally, copying might fail (e.g. if both xclip and xsel are missing or if gitui is being run via ssh). The notification could report that failure instead when it happens. Maybe a good place to catch that error is at the call site of in ?`copy_commit_hash``commitlist.rs`

You are very right, I think it would be very useful to know what text is being copied, on the other hand I also agree with you, I think it is useful to show the error message if the copy fails, in that case I did nothing because I did not know what to do with that error, now I have an idea, so I will be making changes and will update the PR

2022-10-15 10:29 UTC, extrawurst commented on src/components/commitlist.rs
> +const FAIL_COPY: &str = "Failed to copy the Text";
these should go into our separate strings.rs file

2022-10-15 10:29 UTC, extrawurst requested changes
see above

2022-10-15 20:26 UTC, SergioRibera commented on src/components/commitlist.rs
> +const FAIL_COPY: &str = "Failed to copy the Text";
Done

2022-10-18 23:15 UTC, SergioRibera commented
@extrawurst That's it, I fixed all the clippy and formatting errors in the project (I think it should go in another PR but the CI was not working due to some base errors)

Cries in CI/CD *
![image](https://user-images.githubusercontent.com/56278796/196562106-81e427ad-8a67-4a7e-be23-bb733c4ac5c4.png)


If you need any changes, please let me know

2022-10-19 11:50 UTC, extrawurst commented
https://github.com/extrawurst/gitui/pull/1390 is merged now, so please update with current master again

2022-10-19 22:52 UTC, SergioRibera commented
@extrawurst Done, now a query please, what version of rust do you use?

2022-10-20 14:27 UTC, extrawurst commented
Please rebase again and resolve the conflicts so we can merge this

2022-10-24 14:47 UTC, extrawurst commented
please fix the clippy errors

2022-10-25 03:21 UTC, SergioRibera commented
@extrawurst Done 😃

2022-10-26 12:35 UTC, merged

2022-10-26 12:35 UTC, extrawurst commented
Thanks for sticking at this!