Minor refactors and deduplications
extrawurst/gitui pull request #1411
Opened 2022-10-26 15:49 UTC by alexmaco

It changes the following:
- performs some minor refactors

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

2022-11-05 15:45 UTC, extrawurst requested changes

2022-11-05 15:45 UTC, extrawurst commented on src/components/branchlist.rs
> +				self.has_remotes = !self.branches.is_empty();
I think this will only set the `has_remotes` properly if in the local-branchlist, that's not what we want?!

2022-11-23 18:51 UTC, alexmaco commented on src/components/branchlist.rs
> +				self.has_remotes = !self.branches.is_empty();
Indeed, I missed that difference. I'll remove that change.

2023-08-26 12:37 UTC, extrawurst commented
superseded by 5b2b8c7

2023-08-26 12:37 UTC, closed without merging