Checkout commit
extrawurst/gitui pull request #1499
Opened 2023-01-07 12:45 UTC by fralcow

This Pull Request fixes/closes #{983}.

It changes the following:
- Adds a command to a log view to checkout a specific commit

I followed the checklist:
- [x] I added unittests
- [ ] I ran `make check` without errors -- sync::submodules::tests::test_smoke throws an error for me, both in master and my branch: `Error { code: -1, klass: 16, message: "the server did not provide a certificate" }`. I would appreciate some help fixing this.
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

2023-01-29 08:58 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +			git2::build::CheckoutBuilder::new().force(),
this will overwrite changes made to the index, right? I am not sure we want `force` to be true

2023-01-29 08:59 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +		write_commit_file(&repo, "test_2.txt", "test", "commit2");
`write_commit_file` returns the `CommitId`, you don't need to use `LogWalker` to find them

2023-01-29 10:04 UTC, extrawurst requested changes
small improvement on the error handling and this is good to go 💪

2023-01-29 10:04 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +			git2::build::CheckoutBuilder::new().force(),
I tested, it in fact will fail with an `Err` if there are uncommitted changes. se more comments below

2023-01-29 10:04 UTC, extrawurst commented on src/components/commitlist.rs
> +			checkout_commit(&self.repo.borrow(), commit_hash)?;
the fact that it fails if there are uncommitted changes makes this err bubble up here. we should use `try_or_popup` macro here. to show a proper error popup to the user instead of closing the app

2023-01-31 22:00 UTC, fralcow commented on asyncgit/src/sync/branch/mod.rs
> +		write_commit_file(&repo, "test_2.txt", "test", "commit2");
done! thanks for the tip.

2023-01-31 22:29 UTC, fralcow commented on src/components/commitlist.rs
> +			checkout_commit(&self.repo.borrow(), commit_hash)?;
done!

2023-01-31 22:30 UTC, fralcow commented
Thank you for your comments! I've fixed the code, let me know if more stuff needs fixing. :muscle:

2023-02-04 06:00 UTC, merged

2023-02-04 06:00 UTC, extrawurst commented
Thank you @fralcow