Copy file path
extrawurst/gitui pull request #1516
Opened 2023-01-18 07:25 UTC by yanganto

This Pull Request fixes/closes #{issue_num}.

It changes the following:
- allow copy file path in revision files
- allow copy file path in status tree

I followed the checklist:
- [X] This feature is not a git operation, I think we do not need a test on copy feature.
- [X] I ran `make check` without errors
- [X] I tested the overall application
- [X] I added an appropriate item to the changelog

2023-02-11 09:44 UTC, extrawurst requested changes

2023-02-11 09:44 UTC, extrawurst commented on src/components/status_tree.rs
> +			if crate::clipboard::copy_string(&item.info.full_path)
why not use `try_or_popup` here aswell?

2023-02-11 09:44 UTC, extrawurst commented on src/components/status_tree.rs
> +				} else if key_match(e, self.key_config.keys.copy) {
if we add a new event handler we should generally also add a new entry to the command bar

2023-02-11 09:44 UTC, extrawurst commented on src/components/revision_files.rs
> +			} else if key_match(key, self.key_config.keys.copy) {
if we add a new event handler we should generally also add a new entry to the command bar

2023-02-12 05:15 UTC, yanganto commented on src/components/status_tree.rs
> +			if crate::clipboard::copy_string(&item.info.full_path)
The data struct of this component is different from others, so we can not use this macro here.

2023-02-12 10:06 UTC, merged