add fuzzy finder in branch list
extrawurst/gitui pull request #1658
Opened 2023-04-18 12:44 UTC by UUGTech

This PR is related to #1350.

Hi @extrawurst,

Sorry for my poor English. But I have a small PR!
I implemented a fuzzy finder pop-up in the branch list.
This may make it easier to find the branch you want to select.

Instead of a pop-up, we could implement as an embedded finder in the branch list, but I don't think this is a good idea as it would change the look and feel a lot.
So I have implemented it as a pop-up.
The implementation is almost the same as file_find_popup.

It changes the following:
- add branch finder popup to branchlist component

Here is how it works in the implementation in this PR.
![gitui_branch_find_popup](https://user-images.githubusercontent.com/55311933/232778415-1fbf004f-6af9-4adf-b352-085e4ee57a91.gif)

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

2023-04-19 11:11 UTC, extrawurst commented on src/keys/key_list.rs
> +			branch_find: GituiKeyEvent::new(KeyCode::Char('F'),  KeyModifiers::SHIFT),
why did you choose a different hotkey to the file finder?

2023-04-19 11:12 UTC, extrawurst commented on src/strings.rs
> +	pub fn scroll_popup(key_config: &SharedKeyConfig) -> CommandText {
why is there a new one needed here? did we not have that in other places for `up` and `down` already?

2023-04-19 11:16 UTC, extrawurst requested changes

2023-04-19 11:16 UTC, extrawurst commented on src/components/branch_find_popup.rs
> +pub struct BranchFindPopup {
this looks like a lot of copy paste from `FileFindPopup`. can we extract a shared base here? we might want the same for other places too

2023-04-19 11:16 UTC, extrawurst commented on src/components/branch_find_popup.rs
> +	fn commands(
we should also add an entry for the `return` command that closes this finder based on the selection (technically the same as `esc` because we already selected the entry in the background)

2023-04-19 12:40 UTC, UUGTech commented on src/keys/key_list.rs
> +			branch_find: GituiKeyEvent::new(KeyCode::Char('F'),  KeyModifiers::SHIFT),
In remote tab of branchlist component, `f` is already mapped for `fetch`. So I needed to make it different. 
If there is another good hotkey, we can choose it.

2023-04-19 12:41 UTC, UUGTech commented on src/components/branch_find_popup.rs
> +pub struct BranchFindPopup {
Yes, the process is almost the same as `FileFindPopup`, so I will try to make one like a `FuzzyFindPopup` for general use.
Actually, I'm very new to Rust, so it might take a bit of time.

2023-04-19 12:41 UTC, UUGTech commented on src/components/branch_find_popup.rs
> +	fn commands(
Sorry, I forgot to add command info of `return`. I think it already could be closed by `return`. `Esc` also closes based on the selection. This is the same as `file_find_popup`. By the way, command info of `file_find_popup` also dose not have `return`, so I think we need to add it too.

2023-04-19 12:50 UTC, extrawurst commented on src/components/branch_find_popup.rs
> +pub struct BranchFindPopup {
if you commit to following up with that I am fine if we make this a separate issue+PR. if you are up for that please create the issue to mark this as intended to not be part of this PR

2023-04-19 12:50 UTC, extrawurst commented on src/components/branch_find_popup.rs
> +	fn commands(
yeah lets add it in both places. exactly why we need to consolidate both into a common component

2023-04-19 23:36 UTC, UUGTech commented
Ok, when it's ready for the final review, I re-request review.

Before that, I have a small question.
Which is better command info?

`Scroll[...] Close[⎋] Close[⏎]`
`Scroll[...] Close[⎋⏎]`

2023-04-21 21:03 UTC, merged

2023-04-21 21:03 UTC, extrawurst commented
Thanks a lot!

2023-04-22 06:13 UTC, extrawurst commented
added changelog entry for you including gif showcase:
![Uploading Screenflick Movie 9.gif…]()

2023-04-22 08:47 UTC, UUGTech commented
I had completely forgotten about the changelog. 🙇‍♂️
Thank you so much!