Add support for options handling in log and stashes views #1661
extrawurst/gitui pull request #1675
Opened 2023-05-07 08:48 UTC by kamillo

This Pull Request fixes/closes #1661.

It changes the following:
- Adds support for options handling in log and stashes views
- `SharedOptions` are now passed to `InspectCommitComponent` and `CompareCommitsComponent` and used instead of `DiffOptions::default()` 

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

2023-05-09 18:17 UTC, extrawurst requested changes
Looks good. Thanks for taking this! One small comment

2023-05-09 18:17 UTC, extrawurst commented on CHANGELOG.md
> +* add support for options handling in log and stashes views ([#1661](https://github.com/extrawurst/gitui/issues/1661))
Please annotate with your GitHub handle (see other entries)

2023-05-10 05:49 UTC, kamillo commented on CHANGELOG.md
> +* add support for options handling in log and stashes views ([#1661](https://github.com/extrawurst/gitui/issues/1661))
Sure, done.

2023-05-10 12:34 UTC, extrawurst commented
@pm100 mind giving this a spin? I am currently on holiday and can’t test it

2023-05-10 16:52 UTC, pm100 commented
Not quite sure how this has happened (I am also away but have my macbook and can remote into my home windows dev system) something has pulled crossterm 0.26 into gitui. This has a serious breaking change for windows. I already ran across this for tiu-textarea - see https://github.com/rhysd/tui-textarea/pull/17 because , if you recall, I am working on integrating that into gitui (I have pending PR too, hopefully they get to that)

I supposed that its not this PR but something earlier BUT my initial testing suggests its this change (I pulled gitui master branch and it was fine)

The fix is simple if you know where the keyboard event conversion core is. You now need to explictly test that the crossterm key event is a keydown (ct 0.26 on windows also generates a key release event - grr)

If you tell me where to tweak that I can edit it in and test it (remote debugging / exploring of code I dont know is very hard - only one monitor, small screen, and v slow)

BTW. This PR works fine on Mac and Ubuntu (via WSL).

2023-05-17 15:22 UTC, kamillo commented
Let me know if you need any further changes for this PR.

2023-05-17 16:11 UTC, pm100 commented
@kamillo I was testing this on windows and hit a blocking issue pulled in from crossterm 0.26, this is now fixed in master and you have synced with that. I will finish testing tomorrow or the next day

2023-05-17 20:29 UTC, pm100 commented
@extrawaust tested on macos 13.3.1 ubuntu 20.2 (WSL) and windows 11. Works fine

2023-06-19 13:40 UTC, merged