Indicate to the user that a stash save is in progress
extrawurst/gitui pull request #1702
Opened 2023-05-28 23:56 UTC by nrempel

This Pull Request fixes #1495.

It changes the following:
- Add AsyncStash
- Updates `StashMsgComponent` to use AsyncStash instead of sync::Stash
- Introduces disabled flag on `TextInputComponent`
- Change `StashMsgComponent` title to "Stashing..." while stash is pending and disable input

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

2023-05-29 00:00 UTC, nrempel commented on src/components/textinput.rs
> +#[allow(clippy::struct_excessive_bools)]
Note: I saw this elsewhere so I also allowed this rule. Refactoring this not to include 3 bools didn't make sense to me.

2023-06-13 13:38 UTC, extrawurst requested changes

2023-06-13 13:38 UTC, extrawurst commented on src/components/textinput.rs
> +		if self.visible && !self.disabled {
this is pretty invasive. why do we need that? the text input for the stashing can just close IMO and does not need to learn a new state of `disabled`. what is the rational?

2023-06-13 14:12 UTC, xcloudplatform commented
yes we need that

On Tue, Jun 13, 2023 at 4:38 PM extrawurst ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/components/textinput.rs
> <https://github.com/extrawurst/gitui/pull/1702#discussion_r1228149417>:
>
> > @@ -419,7 +432,7 @@ impl Component for TextInputComponent {
>  	}
>
>  	fn event(&mut self, ev: &Event) -> Result<EventState> {
> -		if self.visible {
> +		if self.visible && !self.disabled {
>
> this is pretty invasive. why do we need that? the text input for the
> stashing can just close IMO and does not need to learn a new state of
> disabled. what is the rational?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/extrawurst/gitui/pull/1702#pullrequestreview-1477204931>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAHYDCWC67NGTW2IBWKO3S3XLBUNDANCNFSM6AAAAAAYSETRMI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-06-14 12:28 UTC, extrawurst commented on src/components/textinput.rs
> +		if self.visible && !self.disabled {
@nrempel

2023-06-14 14:06 UTC, nrempel commented on src/components/textinput.rs
> +		if self.visible && !self.disabled {
Without disabled, it's possible to type in the field while the operation is pending.

I suppose we could close the model and continue the operation in the background. In this case, is there a pattern for handling stashing errors if they occur?

2023-06-19 11:46 UTC, extrawurst commented on src/components/textinput.rs
> +		if self.visible && !self.disabled {
yeah that's what I think we should do, what we do in other cases already. just close the text input popup regularly and then the new popup will block any other input and visualise that the stashing is in progress

2023-12-15 08:07 UTC, extrawurst commented
@nrempel are you willing to finish this up?

2023-12-15 16:18 UTC, nrempel commented
Sorry, it's been a very busy year. I may have time to finish this over the holiday break. But I'll close this for now and revive it if needed.

2023-12-15 16:18 UTC, closed without merging