Feat 1757 add signoff option
extrawurst/gitui pull request #1758
Opened 2023-07-13 13:22 UTC by domtac

This Pull Request fixes/closes #1757 .

It changes the following:
- In commit edit via ctrl-s the sign-off feature of git will be toggled

I followed the checklist:
- [x] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

2023-07-13 17:14 UTC, extrawurst requested changes
I would like to keep the impact on the `asyncgit` crate minimal. lets keep the `add_sign_off` as a pub method we expose and lets make the command just add the sign-off part at commit-msg-edit time. this way its not a mode either. the command just triggers the sign-off addition

2023-07-13 17:14 UTC, extrawurst commented on CHANGELOG.md
> +* Support for sign-off of commits [#1757]https://github.com/extrawurst/gitui/issues/1757
please fix format

2023-07-13 17:14 UTC, extrawurst commented on src/components/commit.rs
> +			Mode::Signoff => {
this is not a mode

2023-07-14 06:14 UTC, domtac commented
> I would like to keep the impact on the `asyncgit` crate minimal. lets keep the `add_sign_off` as a pub method we expose and lets make the command just add the sign-off part at commit-msg-edit time. this way its not a mode either. the command just triggers the sign-off addition

Sure thing. Thanks for the remark. I will be off a couple of days. Expect my changes by end of next week latest.
I converted this PR to draft state until I worked in the proposed changes.

2023-07-25 19:23 UTC, domtac commented on CHANGELOG.md
> +* Support for sign-off of commits [#1757]https://github.com/extrawurst/gitui/issues/1757
Thanks, addressed

2023-07-25 19:25 UTC, domtac commented
> > I would like to keep the impact on the `asyncgit` crate minimal. lets keep the `add_sign_off` as a pub method we expose and lets make the command just add the sign-off part at commit-msg-edit time. this way its not a mode either. the command just triggers the sign-off addition
> 
> Sure thing. Thanks for the remark. I will be off a couple of days. Expect my changes by end of next week latest. I converted this PR to draft state until I worked in the proposed changes.

@extrawurst Hi thanks again for the feedback and for the patience until I found time to address your issues.

Please have a look.

2023-07-25 19:35 UTC, extrawurst requested changes

2023-07-25 19:35 UTC, extrawurst commented on CHANGELOG.md
> +* support for sign-off of commits [#1757](https://github.com/extrawurst/gitui/issues/1757)
format still not aligned, please add the author part

2023-07-25 19:35 UTC, extrawurst commented on src/components/commit.rs
> +			sign_off: false,
I think we can do it even easier: no state, just a command that appends the sign-off message. way simpler

2023-07-25 20:13 UTC, domtac commented on CHANGELOG.md
> +* support for sign-off of commits [#1757](https://github.com/extrawurst/gitui/issues/1757)
Oh my. Sorry for that. Now I got it and resolved

2023-07-25 20:16 UTC, domtac commented on src/components/commit.rs
> +			sign_off: false,
Understood. Now hitting `ctrl-s` just appends the sign off string to the commit message. 
This could be done an infinite amount of times right now. 
What do you think, does it make sense to keep the state in the struct so the sign-off can only be added once?

2023-07-29 19:31 UTC, extrawurst commented
LGTM - let's start with a simple version. if you add it twice and forget to clean it its not nice but not a bug right?

2023-07-29 19:39 UTC, domtac commented
> LGTM - let's start with a simple version. if you add it twice and forget to clean it its not nice but not a bug right?

Aboslutely. I would say that putting the sign-off multiple times is rather an inconvenience than a bug. I'd let it like it is.
Thanks for all your comments and time invested

2023-07-29 20:11 UTC, merged

2024-02-27 15:14 UTC, matthiasbeyer commented on src/components/commit.rs
> +				"\n\nSigned-off-by {user} <{mail}>"
There's the `:` missing after the key of the trailer.

2024-02-27 15:14 UTC, matthiasbeyer commented on src/strings.rs
> +				"Sing-off [{}]",
Typo.

2024-02-27 16:13 UTC, extrawurst commented on src/strings.rs
> +				"Sing-off [{}]",
@matthiasbeyer this PR is already merged, could you open a PR fixing the typos?