Jump to commit via sha
extrawurst/gitui pull request #1818
Opened 2023-08-20 18:44 UTC by AmmarAbouZor

This Pull Request fixes/closes #1799

This PR stills work in progress

It changes the following:
- Adds new function the commits-log to jump to commit via its sha
- Default Keybinding is currently `Ctrl-j`
- The input pupop has live validation
- After closing the input box it'll jump to the commit with the matching SHA

The following point need clarification:
- The live validation retrieve the repo with each keystroke to check if the sha is valid via the method  `git2::revparse_single()`. I've tested it with big repos and didn't see any performance hit with it. But we still can make simple live validation (only hash chars, no spaces, length at most 40) If the current implementation's performance isn't good enough.
- The default keybinding 
- Validation error text
- Title and placeholder texts  

I'll add a demo for the current progress

I followed the checklist:
- [ ] I added unittests
- [ ] I ran `make check` without errors
- [ ] I tested the overall application
- [ ] I added an appropriate item to the changelog

2023-08-20 18:51 UTC, AmmarAbouZor commented
Here is a small demo for the current progress

https://github.com/extrawurst/gitui/assets/35040531/619359fa-b4cf-4ba3-9d7d-aedcbccf6444

2023-08-20 18:59 UTC, joyously commented
Does it jump to it even if that SHA is not in the visible list?

2023-08-20 19:06 UTC, AmmarAbouZor commented
@joyously Yes it jumps to any commit is the repository since it uses the well-tested method `select_commit()` in `revlog`

2023-08-21 13:16 UTC, extrawurst commented
> Does it jump to it even if that SHA is not in the visible list?

yes it will only be able to go to commits in the current branch. otherwise it will show an error right now. #81 will introduce looking at all branches and fix this

2023-08-21 13:18 UTC, extrawurst commented
@AmmarAbouZor this looks great. 

To not add yet another command to the log view I would like this to be an option in the new search popup `LogSearchPopupComponent`. Logically it also makes sense to be in there. once this in place I will merge this.

2023-08-22 09:50 UTC, AmmarAbouZor commented
@extrawurst I think it would be better in the search popup too. 
I'd add a new option there `Commit SHA` Or  `Commit Hash` and move the implementation there. 
Could you please have a look at #1816 before. This would save me one merge conflict :wink:

2023-08-22 10:47 UTC, extrawurst commented
#1816 is merged

2023-08-23 08:16 UTC, AmmarAbouZor commented
@extrawurst  Jump to SHA is embedded in `LogSearchPopupComponent`.
- I added a new mode there with the name 'commit hash'
- No other option can be active along with the commit hash mode
- The validation still happens but it's not visible to the users. No execution can happened if the commit hash mode is active and no valid SHA exists


https://github.com/extrawurst/gitui/assets/35040531/5f37692a-90f4-48d3-9251-3ea1fd520b43

2023-08-23 18:52 UTC, AmmarAbouZor commented
Ok I'll get back to the previous implementation with a separate command (currently default `Ctrl-j`) and make the validation better visualized

2023-08-23 19:56 UTC, extrawurst commented
> Ok I'll get back to the previous implementation

but do not add a new popup. Reuse this one please. Make it use a mode neun or something to store what mode it is in at the moment

2023-08-24 13:47 UTC, joyously commented
For accessibility, it's important that information is not conveyed only with color. (7% of men are red/green color blind) 
In the demo, it looked like less than 3 characters was considered invalid, but it matched at 4. Perhaps a better UI would show the matching hashes, which the user could pick from, although that might be a bit much for a terminal... (but the whole point is that the hash is not visible)

2023-08-24 15:20 UTC, AmmarAbouZor commented
> For accessibility, it's important that information is not conveyed only with color. (7% of men are red/green color blind)
In the demo, 

We can show a validation message in the right bottom corner like in the commit popup. (first iteration of this PR used that)


Considering that the users won't type the hashes themselves in the most cases but they will paste from the clipboard, I don't think that implementing an auto-completion here would add more value.
I can though complete the SHA in the textbox once the users have typed enough characters to determine one single commit, but this can confuse the users in case they are typing a commit that doesn't exist in the repository

2023-08-26 11:37 UTC, extrawurst requested changes

2023-08-26 11:37 UTC, extrawurst commented on asyncgit/src/sync/commits_info.rs
> +		let repo = repo(repo_path)?;
please add `scope_time` here so we can see if this is taking significant time

2023-08-26 11:37 UTC, extrawurst commented on src/app.rs
> +
why empty line here?

2023-08-26 11:37 UTC, extrawurst commented on src/keys/key_list.rs
> +	pub log_jump_commit_sha: GituiKeyEvent,
`find_commit_sha`

2023-08-26 11:37 UTC, extrawurst commented on src/queue.rs
> +	OpenLogJumpCommitSha,
not needed. make it feature of existing search pop

2023-08-26 11:37 UTC, extrawurst commented on src/queue.rs
> +	JumpToCommit(CommitId),
not needed. duplicate of `SelectCommitInRevlog()`

2023-08-26 11:37 UTC, extrawurst commented on src/strings.rs
> +pub static POPUP_TITLE_LOG_JUMP_COMMIT: &str = "Jump to Commit";
no needed. reuse search popup

2023-08-26 11:37 UTC, extrawurst commented on src/tabs/revlog.rs
> +				} else if key_match(
make it part of search-popup

2023-08-26 11:37 UTC, extrawurst commented on src/components/log_search_popup.rs
> +	repo: RefCell<RepoPath>,
please compare in other places of code: we have `RepoPathRef` for this

2023-08-26 11:37 UTC, extrawurst commented
> back to the previous implementation

that was not the idea. the command for jump-to-commit-sha should be only available in the search-popup to prevent littering the revlog command list more. it contextually also makes sense to be a sub behaviour of `find`/`search`.

ideally you

2023-08-27 07:29 UTC, extrawurst commented on src/strings.rs
> +				"Commit Sha [{}]",
better `Search Hash` ?

2023-08-27 07:30 UTC, AmmarAbouZor commented
- Commit sha command is shown in LogSearchPopup with the default keybinding `Ctrl-j`
- Validation message is shown on the right bottom corner when the sha is invalid only
- `Esc` in Commit SHA will go back the search popup

https://github.com/extrawurst/gitui/assets/35040531/f8d2c6c5-c561-40ac-9161-59c3a2055003

2023-08-27 07:46 UTC, extrawurst commented
Thanks for sticking with this. Good work! ❤️

2023-08-27 07:46 UTC, merged