Use `nucleo` instead of `fuzzy-matcher`
extrawurst/gitui pull request #1830
Opened 2023-08-23 10:30 UTC by auvred

This Pull Request fixes/closes #1805.

It changes the following:
- replace `fuzzy-matcher` with `nucleo` in `FuzzyFindPopup`

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

--- 

According to the `nucleo` [docs](https://docs.rs/nucleo/0.1.1/nucleo/struct.Matcher.html), the `Matcher` allocates some heap memory at the creation, that's why it should be reused

I'm not sure that this change will be merged, so for now I'll open a draft PR

2023-08-23 16:16 UTC, extrawurst requested changes
please bring up to date with master and remove all usages of `fuzzy-matcher`

2023-08-23 16:16 UTC, extrawurst commented on src/components/fuzzy_find_popup.rs
> +			let mut line_content_buf = Vec::new();
maybe we should also cache these buffers, right?

2023-08-23 16:16 UTC, extrawurst commented on src/components/fuzzy_find_popup.rs
> +			let mut line_content_buf = Vec::new();
maybe just wipe them as soon as one closes the window?

2023-08-23 16:16 UTC, extrawurst commented on Cargo.lock
> -name = "fuzzy-matcher"
is this branch up to date with master? I don't see the removal of `fuzzy-matcher` in `asyncgit` which got introduced in #1791

2023-08-23 21:33 UTC, auvred commented on src/components/fuzzy_find_popup.rs
> +			let mut line_content_buf = Vec::new();
Thank you for the review! I moved them to the `FuzzyFindPopup` alongside the `matcher`. Maybe I should move `matcher` and `matcher_*` to a new struct to omit this prefix?

2023-08-23 21:34 UTC, auvred commented on Cargo.lock
> -name = "fuzzy-matcher"
Sorry, this branch was really outdated, I merged latest changes from master

After a little digging in the [`asyncgit/src/sync/logwalker.rs`](https://github.com/extrawurst/gitui/blob/master/asyncgit/src/sync/logwalker.rs), I realised that it would require more changes than in `fuzzy_find_popup.rs`

The main problem I'm struggling with is the [`fuzzy_match`](https://docs.rs/nucleo/0.1.1/nucleo/struct.Matcher.html#method.fuzzy_match) borrows Matcher as mutable, this will require some changes in the current implementation

The shortest way I see is this: we can wrap `matcher` in `LogFilterSearch` into `RwLock`, this will allow us to borrow filter as mutable only during the actual matching. Otherwise we'll be required to handle the entire filter and closures that borrow it as mutable everywhere (maybe I'm wrong)

Could you please advise how best to implement this?

2023-08-26 12:24 UTC, extrawurst commented on Cargo.lock
> -name = "fuzzy-matcher"
`Mutex` is fine here since we won't have multiple readers and any benefit of `RwLock` for this.

2023-08-26 12:24 UTC, extrawurst commented
btw. I would like to see nucleo mature a bit before we can merge this: https://github.com/helix-editor/nucleo/issues/15

2023-08-28 00:44 UTC, pascalkuthe commented on Cargo.lock
> -name = "fuzzy-matcher"
I am not really aware of how your codebase works but I might mention here that `fuzzy-matcher` uses an implicit internal thread local together with interior mutability to hide the same internal mutability that nucleo has (and has similarly expensive allocations although they are lazy instead of eagerly). So if you are doing the matching in parallel (which I would recommend) the mutex will hinder nucleo and you would get better results by using one matcher instance per thread (the allocation is large but not that large either).  

Btw if you are looking to add an fzf like filter I would really recommend that you consider the high-level nucleo API. It performs the matching in parallel and can perform millions of matches with barely perceptible delay (on a beefy CPU). It's what we use in helix for the file picker (you can try it out by building this branch https://github.com/helix-editor/helix/pull/7814 and running it in your root directory). 

It also supports fully lock-free (and almost always wait-free) parallel streaming so if you are iterating revs in one (or multiple)  background threads that would well too

2023-08-29 13:38 UTC, extrawurst commented
@auvred please update to current master and new nucleo release: https://github.com/helix-editor/nucleo/issues/15#issuecomment-1697448141

2023-08-29 14:39 UTC, auvred commented
I'm a little busy in the next few days, I'll continue working on this PR soon, if it will still be relevant

It seems that it would be better to use the high-level api as pascalkuthe advised :)

2023-08-29 14:42 UTC, extrawurst commented
@auvred its not pressing to get it in. how about reworking it to use the high level API?

2023-08-29 14:43 UTC, auvred commented
I'm all for it!

2023-09-09 09:51 UTC, auvred commented
I will close this pull request for now so as not to interfere with the others who want to implement this feature. So if anyone wants to work on this, fill free to pick it up

2023-09-09 09:51 UTC, closed without merging