add syntax highlighting for blame view (#745)
extrawurst/gitui pull request #1914
Opened 2023-10-03 17:02 UTC by tdtrung17693

This Pull Request fixes/closes #745.

It changes the following:
- Add syntax highlighting for blame view

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

2023-10-13 06:37 UTC, tdtrung17693 commented
Hi @extrawurst, could you take a look into this PR? If there is anything need to change please let me know. Thank you!

2023-10-16 15:35 UTC, extrawurst requested changes

2023-10-16 15:35 UTC, extrawurst commented on src/app.rs
> +		self.blame_file_popup.update_syntax(ev);
i find it misleading to call it `update_syntax` as you do not check for which event it is, so technically its just `update_async` and inside you make sure to react only on the right event

2023-10-16 15:35 UTC, extrawurst commented on src/components/blame_file.rs
> +	///
why some empty comments and some without? consistency please

2023-10-16 15:35 UTC, extrawurst commented on src/components/blame_file.rs
> +			let title_with_highlight_progress = format!(
lets only show the percentage while its loading. no need to confuse with `100%` the whole time after the parsing happened

2023-10-16 15:35 UTC, extrawurst commented on src/components/blame_file.rs
> +			async_highlighting: AsyncSingleJob::new(
i would argue we should put it in an option and only keep it around while there is an async job ongoing and initialize it to `None` first

2023-10-16 15:35 UTC, extrawurst commented on src/components/blame_file.rs
> +						self.async_highlighting.progress();
i have to double check but i think the progress retrieval is pretty lightweight, no need to cache it

2023-10-16 15:35 UTC, extrawurst commented on src/components/blame_file.rs
> +								// *(self.file_blame.s = Either::Left(syntax);
please clean up not needed comments

2023-10-16 15:35 UTC, extrawurst commented on src/components/blame_file.rs
> +				return file_blame
please keep it consistent with the non-return call style, last statement without `;` is the return value

2023-10-16 15:35 UTC, extrawurst commented on src/components/blame_file.rs
> +		self.async_highlighting.spawn(AsyncSyntaxJob::new(
why spawn the same job twice?

2023-10-16 15:38 UTC, extrawurst commented on src/components/blame_file.rs
> +			let title_with_highlight_progress = format!(
nvm i am blind :D

2023-10-17 15:50 UTC, tdtrung17693 commented on src/components/blame_file.rs
> +			async_highlighting: AsyncSingleJob::new(
As I see in the codebase, this is currently the way that other components instantiate the async jobs. Also, keeping this way makes it easier to process the job's result, instead of multi-level pattern-matching.

2023-10-18 07:06 UTC, extrawurst requested changes

2023-10-18 07:06 UTC, extrawurst commented on src/components/blame_file.rs
> +			async_highlighting: AsyncSingleJob::new(
in order to keep things maintainable i started using this pattern successfully in `Revlog` with `LogSearch`.
in our case here we can combine probably 4 member (`async_blame`, `syntax_progress`, `file_blame` and `async_highlighting`) variables into an enum depending on our state and it makes it easier to reason which ones are expected to be valid at what state.

2023-10-18 10:24 UTC, tdtrung17693 commented on src/components/blame_file.rs
> +			async_highlighting: AsyncSingleJob::new(
Looks great. Let me try it.

2023-12-20 20:49 UTC, extrawurst commented on src/components/blame_file.rs
> +			async_highlighting: AsyncSingleJob::new(
What's the status here? Would be great to carry over the finish line!

2023-12-25 20:47 UTC, extrawurst commented on src/components/blame_file.rs
> +			async_highlighting: AsyncSingleJob::new(
Will put it in draft till reworked

2023-12-25 20:48 UTC, extrawurst requested changes
Please update

2024-01-01 04:25 UTC, tdtrung17693 commented on src/components/blame_file.rs
> +			async_highlighting: AsyncSingleJob::new(
I refactored it and combined all those 4 processes into the one below just as you suggested. 

```rust
enum BlameProcess {
	GettingBlame(AsyncBlame),
	SyntaxHighlighting {
		unstyled_file_blame: SyntaxFileBlame,
		job: AsyncSingleJob<AsyncSyntaxJob>,
	},
	Result(SyntaxFileBlame),
}
```

2024-02-12 13:44 UTC, extrawurst requested changes
looks much better. please update to current master and then we can merge

2024-02-19 16:15 UTC, merged

2024-02-19 16:15 UTC, extrawurst commented
@tdtrung17693 thank you so much!