Prevent unsigned tagging
extrawurst/gitui pull request #1915
Opened 2023-10-09 20:50 UTC by TeFiLeDo

This Pull Request fixes/closes no existing issue. Do I need to open one? Can I just link this PR in the change log?

It changes the following:
- Prevents tagging if `tag.gpgsign` is enabled.
- A replica of what #740 and #741 do for commits.

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

2023-10-16 15:18 UTC, extrawurst requested changes

2023-10-16 15:18 UTC, extrawurst commented on src/components/tag_commit.rs
> +	pub fn tag(&mut self) -> anyhow::Result<()> {
why explicitly use `anyhow` here?

2023-10-16 16:12 UTC, TeFiLeDo commented on src/components/tag_commit.rs
> +	pub fn tag(&mut self) -> anyhow::Result<()> {
I have no idea 😅
removed it

2023-10-16 16:12 UTC, TeFiLeDo commented on CHANGELOG.md
> +* do not allow tag when `tag.gpgsign` enabled ([#1915](https://github.com/extrawurst/gitui/pull/1915))
Done

2023-10-16 16:14 UTC, extrawurst commented
There is a merge conflict

2023-10-17 06:38 UTC, extrawurst approved these changes

2023-10-17 06:40 UTC, merged

2023-10-17 06:40 UTC, extrawurst commented
thanks