feat(LogSearch): Allow aborting search
extrawurst/gitui pull request #2000
Opened 2024-01-07 23:54 UTC by StemCll

This Pull Request fixes/closes https://github.com/extrawurst/gitui/issues/1860

It changes the following:
- Adds cancellation_flag to AsyncCommitFilterJob
- cancels LogSearch when pressed `escape`

I followed the checklist:
- [ ] I added unittests
- [ ] I ran `make check` without errors
- [ ] I tested the overall application
- [ ] I added an appropriate item to the changelog

2024-02-12 13:40 UTC, extrawurst requested changes

2024-02-12 13:40 UTC, extrawurst commented on asyncgit/src/filter_commits.rs
> +					}
this is not enough.

the (potentially) expensive filter function might still be called on a batch of 1k commits (which in my test filter also on the commit files can take up to 12s per batch) before realizing that the user aborted.

lets check the cancel flag before each filter function call and benchmark if that makes the normal search (without canceling) noticeably slower

2024-02-14 08:43 UTC, StemCll commented on asyncgit/src/filter_commits.rs
> +					}
Sure, will test it. What's your benchmark suite?

2024-02-14 09:00 UTC, extrawurst commented on asyncgit/src/filter_commits.rs
> +					}
No suite, just observing after setting the abort flag and actually waiting for the cancel to happen to close the hi instead of closing the UI instantly. Then you see it with your own eyes

2024-02-14 10:33 UTC, extrawurst commented on asyncgit/src/filter_commits.rs
> +					}
and to see whether the check inside the inner loop slows down search you can just use the search timing that is already shown in the UI after a search (it shows how long it took)

2024-02-18 13:00 UTC, StemCll commented on asyncgit/src/filter_commits.rs
> +					}
@extrawurst in my search case the first version executed in 114.54053s. The latest one finished in  89.988s <- the check before `filter_map` does a better job (in my case at least...). I don't really like the two filter_maps solution, but couldn't come up with any better option to cancel rayon iterators

2024-02-19 10:40 UTC, extrawurst commented on asyncgit/src/filter_commits.rs
> +					}
so its adds 20s to a normal non-aborted-search if we check the flag in the inner loop?

the problem is that this will close the UI before the search actually ends. i don't want the UI to hide the fact that there is still processing happening. we have to find a better solution then, it cannot be merged like this

2024-02-19 10:41 UTC, extrawurst reviewed
can't be merged in this state

2024-02-20 17:34 UTC, extrawurst commented
finishing it via #2078

2024-02-20 17:34 UTC, closed without merging

2026-02-25 01:33 UTC, robinshen36 commented
@algora-pbc attempt

Just came across this and thought I'd reach out...

Been diving into CLI lately and this seems like a perfect fit.

Thinking of kicking things off by checking the vim keys - does that sound reasonable?

What's the budget looking like? Around $160-$280 feels about right, but flexible.

Talk soon hopefully.