Replace textarea with tui-textarea
extrawurst/gitui pull request #2045
Opened 2024-02-13 00:54 UTC by pm100

PR for #1662 

now using tui-textarea v.04, that adds keyboard based text selection (hold down shift key while moving cursor with mouse)

reminder that a newline is made by pressing ctrl-enter or shift-enter

2024-02-13 01:01 UTC, pm100 commented
still would like to point out that one of the tests fails on windows due to a privilege issue. It would be nice if that test was cfg !windows

2024-02-13 09:43 UTC, extrawurst requested changes
a few nitpicks but ultimately the primary problem is: for me in none of the macos terminals (iterm2, Terminal, vscode embedded) the newline command works

2024-02-13 09:43 UTC, extrawurst commented on src/components/textinput.rs
> +#![allow(unused_imports)]
lets not

2024-02-13 09:43 UTC, extrawurst commented on src/components/textinput.rs
> +	completely rewritten using tui-textarea as it provides a ton of useful features
lets write comments as-is not as-compared-to-before. comments on the diff belong into the PR desciption

2024-02-13 09:43 UTC, extrawurst commented on src/components/textinput.rs
> +New line is shift-enter, ctrl-enter . These are all common new line editor commands (discord, emacs,...)
neither of the two work for me on mac-os. lets make them work & show up in the command list

2024-02-13 09:43 UTC, extrawurst commented on src/components/textinput.rs
> +but there are 10-15 ctrl key codes. I could add then to the general help popup, or make a special one for textinput
I like the idea of a specific help popup for the editor

2024-02-13 09:43 UTC, extrawurst commented on src/components/textinput.rs
> +	selecting: bool,
these two selection specific ones probably make sense to be an enum or struct and might fix the struct_excessive_bools-warning.

2024-02-13 09:43 UTC, extrawurst commented on src/components/textinput.rs
> +		let eat_white_space = strings::symbol::WHITESPACE;
if this PR removes needing `strings::symbol::WHITESPACE` then lets remove it instead of this stunt

2024-02-13 09:43 UTC, extrawurst commented on src/components/textinput.rs
> +		self.msg.take(); // = String::new();
comment not needed

2024-02-13 09:43 UTC, extrawurst commented on src/components/textinput.rs
> +	// the fancy footwork with the OnceCell is to allow
lets put the comment (non doc comment) inside the fn

2024-02-13 09:43 UTC, extrawurst commented on src/components/textinput.rs
> +		self.msg.take();
instead of `take`+`set` we can just do `self.msg = msg.into();`, right?

2024-02-13 23:16 UTC, pm100 commented
Its odd because I partially developed on mac so this shift-enter must be new-ish problem. Anyway there is a crossterm issue that I have reported (https://github.com/crossterm-rs/crossterm/issues/861). It is immediately resolvable by changing the startup code of gitui where it sets up crossterm. But that only works in some terminals (ITerm2 works, apple terminal does not).

I can also put back the ctrl-M code for newline that was there way back but one early reviewer said they didnt like it so I took it out.

I will wait a few days to see what crossterm has to say

2024-02-13 23:16 UTC, pm100 commented on src/components/textinput.rs
> +		let eat_white_space = strings::symbol::WHITESPACE;
OK, I got fixated on keeping the changes to one file

2024-02-14 00:02 UTC, pm100 commented on src/components/textinput.rs
> +		self.msg.take();
I thought there had to be a way to do it in one call.

2024-02-14 00:56 UTC, pm100 commented
temp close while trying out fixes

2024-02-14 01:11 UTC, pm100 commented
I have added ctrl-m back , meaing 'new line'

I have added the code to partially fix the mac issue, in my tests it works on iterm2, but not plain terminal. I dont think thats a good way to do it since its now not 100% clear to the user what will work when. The code is there so you can verify that it works.

Fixed everything else (pedantic is a pain, I think some things are less clear now, but whatever..)

Regarding adding help popup , extra key help etc... Can we get this big change in first. Everything works as before so nobody looses anything by not knowing the keystrokes

2024-02-14 11:54 UTC, extrawurst commented
@pm100 I went back through https://github.com/extrawurst/gitui/pull/509 which contains most of the considerations around this new-line command issue. lets go back to that original plan and use a new binding like `ctr+o` to commit and raw `enter` for the newline.

2024-02-14 17:35 UTC, pm100 commented
I think thats a really bad idea, people will hate it

- its a breaking change
- its a breaking change to the most often used path through gitui ('gitui', 'a','c','xxxxx', 'enter')
- its a breaking change that is introduced solely to enable a feature that will not be used 99% of the time (multi line commit messages)
- its not obvious that ctrl-o means commit. It feels like 'open' to me
- its a breaking change caused by working around a bug in crossterm that only affects mac users using the native terminal

If you use my suggestion (ctrl-m for new line) then the feature is enabled, and nothing breaks, its an obscure key combination for use in a rare case. And maybe disable ctrl-enter on terminals where it doesnt work. 

Its your codebase but I guarantee you will annoy lots of users. Including me, because my muscle memory will still hit enter every time (just like I hit Esc every time to close a popup dialog because that seems natural - and it does close many popups, Annoys me every time it happens). I will be annoyed but at least I know the solution, others will not know what to do.

2024-02-14 17:44 UTC, extrawurst commented
i am unsure:

its been a long discussion prior. see old PR. 

its not a stable version of gitui yet, it will be documented in the cmd-bar. if anything can be broken its before 1.0.

Plus: your muscle memory will lead to no breaking change, you will insert a new-line, newcomers might be put of by the fact right now that enter is not a new-line and does a commit.

plus plus: you can re-bind the command if you want to.

2024-02-14 19:52 UTC, pm100 commented
How about this
- I make it so that you can specify the key binding for new line (not doable at the moment )
-  I make it so there is only one binding for newline (there are multiple ones now, and your key config does not support that)
- I add to the bottom line of the text input box text saying something like 'ctrl-n=newline'
- I make the default ctrl-n (I dont like ctrl-M - its a default from tui-textarea but I override all those anyway, I think it comes from emacs)
- I think the commit = enter keystroke is also configurable, if not I will make it so.

Making it hard to do the no brainer thing is a really bad idea. But with the above changes people who want to make it hard to do the 99% case and easy to do the 1% case can do exactly that. Everybody happy.

2024-02-14 23:14 UTC, pm100 commented
I have modified the PR so that all the changes I suggest are there, just so you can test it out and see

Here is the key config file for people who like it the hard way :-)
```
(
  multiline_enter: Some((code:Char('o') , modifiers:"CONTROL")),
  textbox_newline: Some((code:Enter, modifiers:"NONE")),
)
```

Includes fixing the textinput clients that should be single line (like branch name etc)

2024-02-15 20:35 UTC, extrawurst requested changes
thanks for sticking with this. i think we are getting closer. i added a bunch of comments here and there.

2024-02-15 20:35 UTC, extrawurst commented on src/components/create_branch.rs
> +			.with_input_type(InputType::Singleline),
hm good catch, this was already an oversight before but now its getting to be a very small input field. let me see if I can fix that on master separately

2024-02-15 20:35 UTC, extrawurst commented on src/components/create_branch.rs
> +			.with_input_type(InputType::Singleline),
<img width="612" alt="Screenshot 2024-02-15 at 21 00 51" src="https://github.com/extrawurst/gitui/assets/776816/46925689-c02e-40da-968e-22122c397738">

2024-02-15 20:35 UTC, extrawurst commented on src/keys/key_list.rs
> +			textbox_newline: GituiKeyEvent::new(KeyCode::Char('r'),  KeyModifiers::CONTROL),
lets call it just `newline`

2024-02-15 20:35 UTC, extrawurst commented on src/main.rs
> +		stdout().execute(LeaveAlternateScreen).map(|_f| ());
lets leave it consistent with above, this change is not needed

2024-02-15 20:35 UTC, extrawurst commented on src/main.rs
> +		crossterm::queue!(io::stdout(), PopKeyboardEnhancementFlags)
i dont know yet how to reproduce this but I get this printed after closing gitui using this branch:

```
PopKeyboardEnhancementFlags failed%
```

how can we get rid of this?

2024-02-15 20:35 UTC, extrawurst commented on src/components/textinput.rs
> +#[allow(clippy::struct_excessive_bools)]
this allow is not needed anymore

2024-02-15 20:35 UTC, extrawurst commented on src/components/textinput.rs
> +
consistency: no empty line between doc comment and fn

2024-02-15 20:35 UTC, extrawurst commented on src/components/textinput.rs
> +		if self.is_visible() {
why recreate the whole textarea ?

2024-02-15 20:35 UTC, extrawurst commented on src/components/textinput.rs
> +			self.create_and_show();
why recreate the whole textarea ?

2024-02-15 20:35 UTC, extrawurst commented on src/components/textinput.rs
> +	fn create_and_show(&mut self) {
lets call it `create_inner_textarea`

2024-02-15 20:35 UTC, extrawurst commented on src/components/textinput.rs
> +	fn draw_newline_hint<B: Backend>(
<img width="868" alt="Screenshot 2024-02-15 at 21 24 22" src="https://github.com/extrawurst/gitui/assets/776816/51286099-28b7-4a13-b6ae-940eff1d09fc">

lets use the machinery that is already there to feed this new command into the cmd-bar on the bottom see `fn commands`

2024-02-15 21:30 UTC, pm100 commented on src/main.rs
> +		crossterm::queue!(io::stdout(), PopKeyboardEnhancementFlags)
since we are not using ctrl/shift enter anymore I will remove all these changes, I dont really understand why they work, people can set it up using keyboard override if they want, but they will only do it if it works (ie not on a mac). Revisit if crossterm fixes their issue

2024-02-15 21:34 UTC, pm100 commented on src/components/textinput.rs
> +			self.create_and_show();
Dont go there :-). This code is the result of > 6 months of work arm wrestling with tui-textarea, your API into textarea (which I took as a given) and rust lifetime management.

2024-02-15 21:40 UTC, pm100 commented on src/components/commit.rs
> +				if key_match(e, self.key_config.keys.multiline_enter)
Its a bit more fiddly than that . What should the behavior be for other multi-line edit boxes. For example 'reword commit'. I also wonder about stash name dialog, I changed it to be single-line but I think thats wrong, it can be a multi-line commit style message. Do all those behave the same way? If so (and I should check that they do work) them maybe 'commit' isnt the best name

2024-02-15 21:50 UTC, pm100 commented on src/components/textinput.rs
> +	fn draw_newline_hint<B: Backend>(
i missed that, will change

2024-02-15 22:20 UTC, pm100 commented
OK. we are close :-)

I did everything you said. 

Notes: 

Should stash msg dialog be multi or single? I made it single but I think it should be multiple. Not sure tho. If multiple I need to change the plumbing around it too.

The defaults are Enter = commit, ctrl-r = newline. I have test both these

```
(
commit: Some((code:Char('o') , modifiers:"CONTROL")),
newline: Some((code:Enter, modifiers:"NONE")),
)
```
which is the one you asked for at the start

and

```
(
commit: Some((code:Enter , modifiers:"NONE")),
newline: Some((code:Enter, modifiers:"SHIFT")),
)
```

Which is what I originally had but doesnt work on a mac - as you found out.

2024-02-15 22:23 UTC, closed without merging