add support for external ssh signing
extrawurst/gitui pull request #2198
Opened 2024-04-19 01:04 UTC by seanaye

TODO
- [ ] add tests

This Pull Request fixes/closes #{2188}.

It changes the following:
- Adds support for external bin signing with ssh keys
-

I followed the checklist:
- [ ] I added unittests
- [ ] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

2024-04-21 16:05 UTC, extrawurst commented
@yanganto you are the most prominent user of ssh-signing. can you review this?

2024-04-21 16:06 UTC, extrawurst commented
@seanaye is there a way to write a test for this?

2024-04-29 16:34 UTC, seanaye commented
I'll try to write some tests this week

2024-04-29 16:41 UTC, kucho commented
Very excited about this feature to start using gitui as my daily driver! Thank you, @seanaye 🙏

2024-05-08 08:19 UTC, b1nhack commented
Thanks a lot, I'm waiting for this feature.

2024-07-04 03:26 UTC, dkarter commented
Thank you for working on this! would love to see it released

2024-08-31 13:43 UTC, seanaye commented
@robrecord no worries! I actually totally forgot about this, I think I can find some time this week to finish it up

2024-08-31 20:46 UTC, seanaye commented
@extrawurst @yanganto please let me know what else I can do to help get this merged

2024-09-01 14:03 UTC, yanganto commented
> @extrawurst @yanganto please let me know what else I can do to help get this merged

Hi @seanaye, 
The previous suggestion about no additional struct in the PR may not help you merge this PR, but it is good to respond if you don't think we need any changes.

2024-09-01 14:26 UTC, extrawurst commented
@kucho @dkarter @robrecord anyone who can help by building this branch and testing it with their setup and reporting back here can help get this merged.

2024-09-02 14:53 UTC, seanaye commented
> > @extrawurst @yanganto please let me know what else I can do to help get this merged
> 
> 
> 
> Hi @seanaye, 
> 
> The previous suggestion about no additional struct in the PR may not help you merge this PR, but it is good to respond even if you don't think we need any changes. 

I'm not quite sure what you mean by this, I don't see any previous feedback. If you review the PR I'm happy to make changes

2024-09-03 01:05 UTC, yanganto commented on asyncgit/src/sync/sign.rs
>  }
Sorry, I found out the review is in stash not publish.

2024-09-04 02:14 UTC, seanaye commented on asyncgit/src/sync/sign.rs
>  }
@yanganto Thanks for your comments. In my opinion having 2 smaller, but higher quality structs is preferable over having a single large struct. With this new suggestion the type system can encode invalid information for example 

```
program: None,
tmp_file: None,
secret_key: None
```

would be a representable type but is not valid. 

I also find that having more, smaller structs has better separation of concerns because each struct has a smaller distinct meaning.

If you feel strongly about your suggestions I can make the change but in my opinion this might make the code harder to maintain, not easier.

2024-09-06 23:36 UTC, yanganto commented on asyncgit/src/sync/sign.rs
>  }
It is a suggestion, I did not againat this PR if you think the another struct is good.  It also works for me.

2024-09-06 23:49 UTC, seanaye commented on asyncgit/src/sync/sign.rs
>  }
I will do which ever one you prefer as you are a maintainer. I wrote code that I would prefer to maintain but it is your choice.

2024-09-11 07:25 UTC, yanganto commented
Does it work with `gpg.program = gpg2`?
What program have we already tested?  

It will be good to have a CI if we want to make sure this feature always works in the future.

2024-09-14 18:07 UTC, seanaye commented
> Does it work with `gpg.program = gpg2`?
> 
> What program have we already tested?  
> 
> 
> 
> It will be good to have a CI if we want to make sure this feature always works in the future.

I have tested so far with the 1Password ssh agent but the CLI arguments are standardized as far as I know

https://developer.1password.com/docs/ssh/git-commit-signing/

I think adding this to CI may be difficult as it would require adding new system dependencies to the image where the CI runs. For example installing the 1Password CLI inside a docker image.

2024-09-30 11:41 UTC, extrawurst commented on asyncgit/src/sync/sign.rs
>  }
An extra struct seems reasonable to me if it bundles up separated logic. If all other concerns are considered please resolve this thread @yanganto

2024-10-01 17:38 UTC, yonas commented
Ping

2024-10-14 04:12 UTC, yanganto requested changes

2024-10-14 04:14 UTC, yanganto commented
I thought the `dbg!`, `eprintln!`, and `debug_cmd_print!` in this project is only in used in test cases, if I am wrong please also let me know.  Thanks.  :pray:

2025-03-06 01:37 UTC, seanaye commented
Sorry for the late reply, I have removed the dbg and rebased to fix conflicts. I did have this working locally at one point but I have changed my workflow to no longer use `git` and thus I can no longer use gitui. 

The issue that you encountered would suggest that the program is not correctly reading the gpg format ssh. I would maybe suggest trying to insert a debug statement and rebuild to see what the value is at runtime. 

This is unfortunately the furthest I can contribute to this PR due to other priorities coming up. Please feel free to either continue this work or close

2025-03-07 15:54 UTC, seanaye commented
If you are curious about life after git, I am using [jj](https://github.com/jj-vcs/jj) on both personal and professional projects

2025-08-19 12:09 UTC, robrecord commented
I'm sorry that I have not been able to review or further this PR. I have not been able to get it working, and I don't have enough (any) experience in rust to be able to contribute at this point. Currently, due to the issues this PR is designed to mitigate, my workflow with gitui is broken and I have to do the actual commit in a separate terminal window. I hope one day this can be resolved or that I can dedicate some time to rust in order to help close this PR.

2026-07-01 08:05 UTC, closed without merging