Support `options` in `git_status.fetch()`
extrawurst/gitui pull request #2287
Opened 2024-07-06 00:36 UTC by kanielrkirby

It looks like support was available/built-in, but possibly left out for some reason?

Happy to rework, this is just to start conversations :)

This Pull Request fixes/closes #2263.

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [ ] I added an appropriate item to the changelog

It would also be good to know your stance on the `?` idea, or any other additions you might want to this to make this mergeable.

2024-07-06 00:41 UTC, kanielrkirby commented
I just realized I got it backwards! That is totally my bad :sweat_smile:

2024-07-06 22:25 UTC, extrawurst commented
thanks for looking into this. i wonder what blame tells us how this got overseen - I assume no one ever used it so it went unnoticed 🙈

2024-07-06 23:58 UTC, kanielrkirby commented
> thanks for looking into this. i wonder what blame tells us how this got overseen - I assume no one ever used it so it went unnoticed 🙈

It seems to be! To be completely fair, most people (myself included) don't know how Git works in most cases. All you usually need is the good ol' `clone <repo>; add <things>; commit -m <changes>; push;`

I remember seeing this was from Stephan Dilly (though I'm not sure who that is, he's in a lot of the old code. Is that your old handle / name perhaps? Or an old maintainer?)

After blaming (using the recursive blame I just added! haHA!!), the project at that point was (as far as I can tell) fully able to support it (the options were there already). Maybe it was just planned to be done in a separate commit.

2024-07-21 16:08 UTC, ondrej-ivanko commented
I'm glad someone is working on this. Thank you guys. I use stashing a lot, so this would definitely help me.

 I suppose this solution doesn't really change anything in the functionality, when user swaps different values in `Options` -> `Status` -> `Show untracked` on Stash tab [4]. In my case switching to different values in the `Show untracked` option doesn't change what files are displayed on Stash tab [4], only what files are displayed on Status tab [1].

2025-03-20 15:21 UTC, naseschwarz requested changes
Hi!

I've noticed a minor snag with the --keep-index logic in your PR.

If you were to fix that and please add an entry to CHANGELOG.md, I'd say we're good to go, though.

2025-03-20 15:21 UTC, naseschwarz commented on src/tabs/stashing.rs
> +				StatusType::WorkingDir
My expectation here would be, that this file list shows all those files, which would be included in a stash.

Here's `--keep-index`'s description:

```
      -k, --keep-index, --no-keep-index
           This option is only valid for push and save commands.

           All changes already added to the index are left intact.
```

I.e. "keep index" has no effect on whether a change in the index is stashed or not. It just affects whether that change is removed from the index and work tree afterwards.

Thus, I would have expected that whether "keep index" is active or not has no effect on whether that file is listed here.

2025-12-06 13:07 UTC, extrawurst commented
@kanielrkirby are you committed to help push this over the finish line?

2025-12-16 03:53 UTC, closed without merging