Remotes popup
extrawurst/gitui pull request #2350
Opened 2024-09-03 13:27 UTC by robin-thoene

This Pull Request fixes/closes #2172 .

It changes the following:
- new popups to interact with git remotes to
  - view remotes
  - add a new remote
  - edit an existing remote name
  - edit an existing remote url
  - delete an existing remote

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

2024-09-17 09:19 UTC, extrawurst commented
any idea why the background color of selection does not span the whole width?

<img width="423" alt="Screenshot 2024-09-17 at 11 18 14" src="https://github.com/user-attachments/assets/bba691c8-a314-4219-b704-cbf5ccabd049">

also i would like us to use as little space as possible for the details, that way we can have more space for the remotes list area

2024-09-17 09:24 UTC, extrawurst commented
not sure why but when the layout only has room for the name in details it still wont show it:

<img width="341" alt="Screenshot 2024-09-17 at 11 23 38" src="https://github.com/user-attachments/assets/de16e357-a8c5-42de-a696-ebe07bf142c8">

2024-09-17 09:27 UTC, extrawurst commented
there are potential panics if you resize your terminal to zero, that we should cover before merge:
```
PanicHookInfo { payload: Any { .. }, location: Location { file: "/Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.27.0/src/widgets/clear.rs", line: 37, col: 21 }, can_unwind: true, force_no_backtrace: false }
trace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/backtrace/libunwind.rs:116:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/capture.rs:197:9
   3: backtrace::capture::Backtrace::new
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/capture.rs:162:22
   4: gitui::set_panic_handlers::{{closure}}
             at /Users/stephan/code/gitui/src/main.rs:382:19
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2084:9
      std::panicking::rust_panic_with_hook
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:808:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:674:13
   7: std::sys::backtrace::__rust_end_short_backtrace
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
   8: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   9: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
  10: ratatui::buffer::buffer::Buffer::index_of
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.27.0/src/buffer/buffer.rs:137:9
      ratatui::buffer::buffer::Buffer::get_mut
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.27.0/src/buffer/buffer.rs:105:17
      <ratatui::widgets::clear::Clear as ratatui::widgets::WidgetRef>::render_ref
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.27.0/src/widgets/clear.rs:37:17
      <ratatui::widgets::clear::Clear as ratatui::widgets::Widget>::render
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.27.0/src/widgets/clear.rs:29:9
  11: ratatui::terminal::frame::Frame::render_widget
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.27.0/src/terminal/frame.rs:75:9
  12: <gitui::components::textinput::TextInputComponent as gitui::components::DrawableComponent>::draw
             at /Users/stephan/code/gitui/src/components/textinput.rs:642:4
  13: <gitui::popups::create_remote::CreateRemotePopup as gitui::components::DrawableComponent>::draw
             at /Users/stephan/code/gitui/src/popups/create_remote.rs:37:4
```

2024-09-17 09:29 UTC, extrawurst requested changes
Ok i finally had time for an in-depth review. i love this feature already just for reviewing PRs :)
Lets get it over the finish line. i believe my remarks are all no biggies but should be addressed before we can merge it.
good job!

2024-09-17 09:29 UTC, extrawurst commented on CHANGELOG.md
> +* update `gix-path` because previous version contained a vulnerability [[@robin-thoene](https://github.com/robin-thoene)] ([#2350](https://github.com/extrawurst/gitui/pull/2350))
please rebase so we do not see changes merged into master

2024-09-17 09:29 UTC, extrawurst commented on src/popups/create_remote.rs
> +		if let Some(n) = self.provided_name.borrow() {
lets name this a bit more readably as `name`.

2024-09-17 09:29 UTC, extrawurst commented on src/popups/remotelist.rs
> +		const THREE_DOTS: &str = "...";
we already have two places where we duplicate this. probably should be a separate cleanup PR, to not dilute this one

2024-09-17 09:29 UTC, extrawurst commented on src/popups/remotelist.rs
> +		for (i, remote) in self
this can be done functionally, so we do not have to worry about `with_capacity` above

2024-09-17 09:29 UTC, extrawurst commented on src/popups/remotelist.rs
> +impl DrawableComponent for RemoteListPopup {
this does not subscribe to remotes being changed, right now, correct? we should do that as a followup

2024-09-17 09:34 UTC, extrawurst commented on src/popups/remotelist.rs
> +		for (i, remote) in self
please see [a806830](https://github.com/extrawurst/gitui/pull/2350/commits/a806830ecba44775c2ab27f036593fdfa106ac66) and check if this can be used in more places in the other popups (this is a refactoring we need to apply more broadly across the code base so no wonder you did not see it before

2024-09-17 09:47 UTC, extrawurst commented on src/popups/remotelist.rs
> +		for (i, remote) in self
ok my change triggered an odd clippy warning which made me check what Text::from_iter does and it simply collects into a `Vec` so we can use a simply `Text::from((..).collect)` too

2024-09-17 15:36 UTC, robin-thoene commented on CHANGELOG.md
> +* update `gix-path` because previous version contained a vulnerability [[@robin-thoene](https://github.com/robin-thoene)] ([#2350](https://github.com/extrawurst/gitui/pull/2350))
done, I will  do this for additional commits that solve the other comments as well

2024-09-17 15:37 UTC, robin-thoene commented on src/popups/create_remote.rs
> +		if let Some(n) = self.provided_name.borrow() {
done

2024-09-17 15:41 UTC, robin-thoene commented on src/strings.rs
> +	format!("Confirm deleting remote {remote_name}")
done

2024-09-17 15:48 UTC, robin-thoene commented on src/popups/remotelist.rs
> +impl DrawableComponent for RemoteListPopup {
I am not 100% sure if I understand this correctly. Let me describe what I have done:

I added a new event "REMOTES" in "queue.rs". That is used in the new remote list popup so that creating, editing and deleting remotes automatically refreshes the current remote list displayed inside the popup (it is handled in "app.rs" similar to how the branch popup handles it).

2024-09-17 15:51 UTC, robin-thoene commented
> any idea why the background color of selection does not span the whole width?
> <img alt="Screenshot 2024-09-17 at 11 18 14" width="423" src="https://private-user-images.githubusercontent.com/776816/368101084-bba691c8-a314-4219-b704-cbf5ccabd049.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODgwMTksIm5iZiI6MTcyNjU4NzcxOSwicGF0aCI6Ii83NzY4MTYvMzY4MTAxMDg0LWJiYTY5MWM4LWEzMTQtNDIxOS1iNzA0LWNiZjVjY2FiZDA0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxNTQxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjZiYjUzNjY1Y2RmOTQ1ZTNlNjc0YzUyOWVjYmRiNDBjOWI4NzExNDAzZmYzYWE0MTA4OTBjNjg2NTAxNTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-6_dyck-MidePALpjQWXepi_irOSJnF9GG1LQ_3_BDA">
> 
> also i would like us to use as little space as possible for the details, that way we can have more space for the remotes list area

I am not 100% sure why this is the case. In the following screenshot I opened the branch popup (prod gitui on my system, not my branch version!) and it has the same issue:

![image](https://github.com/user-attachments/assets/dbd92313-aa6f-4987-8437-0f0ee4a494f8)

2024-09-17 17:15 UTC, robin-thoene commented
> not sure why but when the layout only has room for the name in details it still wont show it:
> <img alt="Screenshot 2024-09-17 at 11 23 38" width="341" src="https://private-user-images.githubusercontent.com/776816/368103122-de16e357-a8c5-42de-a696-ebe07bf142c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTAzODUsIm5iZiI6MTcyNjU5MDA4NSwicGF0aCI6Ii83NzY4MTYvMzY4MTAzMTIyLWRlMTZlMzU3LWE4YzUtNDJkZS1hNjk2LWViZTA3YmYxNDJjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxNjIxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YThiMzgyMzcxZWE3YjVkYTM2ZTg0NmVmNGNlNDY5MWY1N2JlZWE0Y2IyYmRjY2YxNDZkODAyZGUzMDZjMmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pFxeH4ZlCU2X2Ht09BlBuzW_yA3_9hHQKx4MuClwmgM">

I think I solved this now

2024-09-17 18:20 UTC, extrawurst commented
something is still odd rescaling around here:
https://github.com/user-attachments/assets/5af387e1-04a1-4e15-8d6a-837e6ad429c4

2024-09-17 18:24 UTC, extrawurst commented
here seems another issue:
<img width="629" alt="Screenshot 2024-09-17 at 20 23 02" src="https://github.com/user-attachments/assets/016a1753-e92a-438c-92f0-982799d1d587">

2024-09-17 18:26 UTC, extrawurst commented on src/popups/remotelist.rs
> +impl DrawableComponent for RemoteListPopup {
lets cut that into a followup

2024-09-17 18:27 UTC, extrawurst commented
Can you please retry the scaling to 0 with all new popups. i just tried the `rename` one:

```
PanicHookInfo { payload: Any { .. }, location: Location { file: "/Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.28.1/src/buffer/buffer.rs", line: 238, col: 13 }, can_unwind: true, force_no_backtrace: false }
trace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/backtrace/libunwind.rs:116:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/capture.rs:197:9
   3: backtrace::capture::Backtrace::new
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/capture.rs:162:22
   4: gitui::set_panic_handlers::{{closure}}
             at /Users/stephan/code/gitui/src/main.rs:382:19
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2084:9
      std::panicking::rust_panic_with_hook
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:808:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:674:13
   7: std::sys::backtrace::__rust_end_short_backtrace
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
   8: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   9: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
  10: ratatui::buffer::buffer::Buffer::index_of::{{closure}}
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.28.1/src/buffer/buffer.rs:238:13
      core::option::Option<T>::unwrap_or_else
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:1015:21
      ratatui::buffer::buffer::Buffer::index_of
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.28.1/src/buffer/buffer.rs:237:46
      <ratatui::buffer::buffer::Buffer as core::ops::index::IndexMut<P>>::index_mut
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.28.1/src/buffer/buffer.rs:540:21
  11: ratatui::widgets::paragraph::Paragraph::render_text
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.28.1/src/widgets/paragraph.rs:445:24
      ratatui::widgets::paragraph::Paragraph::render_paragraph
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.28.1/src/widgets/paragraph.rs:421:13
      <ratatui::widgets::paragraph::Paragraph as ratatui::widgets::WidgetRef>::render_ref
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.28.1/src/widgets/paragraph.rs:398:9
  12: <ratatui::widgets::paragraph::Paragraph as ratatui::widgets::Widget>::render
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.28.1/src/widgets/paragraph.rs:389:9
  13: tui_textarea::widget::<impl ratatui::widgets::Widget for &tui_textarea::textarea::TextArea>::render
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui-textarea-0.6.1/src/widget.rs:170:9
  14: ratatui::terminal::frame::Frame::render_widget
             at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.28.1/src/terminal/frame.rs:87:9
  15: <gitui::components::textinput::TextInputComponent as gitui::components::DrawableComponent>::draw
             at /Users/stephan/code/gitui/src/components/textinput.rs:646:4
  16: <gitui::popups::rename_remote::RenameRemotePopup as gitui::components::DrawableComponent>::draw
             at /Users/stephan/code/gitui/src/popups/rename_remote.rs:31:4
```

2024-09-17 18:32 UTC, extrawurst commented on src/popups/remotelist.rs
> +		const THREE_DOTS: &str = "...";
marked for follow-up

2024-09-17 18:58 UTC, extrawurst commented
when I "rename" but then leave the name as is:
would be better to just dont error :)
<img width="643" alt="Screenshot 2024-09-17 at 20 57 49" src="https://github.com/user-attachments/assets/a0949986-e5ce-4d96-83c4-3608944833ee">

2024-09-17 19:07 UTC, extrawurst commented
hm this should be addressed:
https://github.com/user-attachments/assets/6fe27e73-f18d-4f97-922c-199fbe8cfd0f

2024-09-18 11:44 UTC, extrawurst commented
ok two last things:
* satisfy clippy
* fix the selection after remooving an entry because it disappears if it was the last element:


https://github.com/user-attachments/assets/e258342a-780b-4e23-81a7-a509e7590d4d

2024-09-18 14:03 UTC, extrawurst approved these changes

2024-09-18 14:31 UTC, merged

2024-09-18 14:31 UTC, extrawurst commented
Thank you so much 🎉

2024-09-18 16:14 UTC, robin-thoene commented
Thank you so much for the review, guidance and help!