WIP: Support reword in log tab
extrawurst/gitui pull request #312
Opened 2020-10-07 22:53 UTC by WizardOhio24

No more do we have to go though an interactive rebase in which the exact commit reference must be known, where we then must choose 'reword' on the correct commit.

This PR provides the reword functionality on the log(commit list) tab, simply press 'r' on the commit, type in the new message and press enter to change it.

This does not do an interactive rebase in git2rs, rather a slightly more complex rebase operation which achieves the same thing (there is no such thing as an interactive rebase in git2rs/libgit2)
This does not work on the first commit because it has no parent.

Linked to #32

2020-10-08 07:46 UTC, extrawurst requested changes
Thanks for looking into this!❤️

2020-10-08 07:46 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +pub fn reword(
I don't think we should expose this as `pub`

2020-10-08 07:46 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +        // repo.find_annotated_commit(commit_oid)?
are you still investigating this?

2020-10-08 07:46 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +                    .expect("Branch name is not valid utf8"),
why panic instead of returning the error using `?`? We have `Utf8Error` for this in error

2020-10-08 07:46 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +            target = rebase.commit(None, &sig, Some(message))?; //Some(message))?;
what's with the commented code?

2020-10-08 07:46 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +            &cur_branch_name.expect("Couldn't unwrap branch name"),
see above

2020-10-08 07:46 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +            &cur_branch_ref.expect("Couldn't unwrap branch name"),
see above

2020-10-08 07:46 UTC, extrawurst commented on src/components/reword.rs
> +        self.input.set_text(commit.message.expect("").combine());
handle as `Result`

2020-10-08 10:48 UTC, WizardOhio24 commented on asyncgit/src/sync/rebase.rs
> +        // repo.find_annotated_commit(commit_oid)?
For now, I don't think this needs to handle the first commit.  It is very rare that someone would want to go back to the very start and change the very first commit.

2020-10-08 10:49 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +        // repo.find_annotated_commit(commit_oid)?
ok

2020-10-10 22:12 UTC, WizardOhio24 commented
This does work, but it doesn't keep it's commit selection prior to the change, it just goes to the top.

2020-10-10 22:31 UTC, WizardOhio24 commented
Fixed

2020-10-25 14:27 UTC, extrawurst requested changes

2020-10-25 14:27 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +                    .expect("Branch name is not valid utf8"),
we have `Utf8Error` for this

2020-10-25 14:27 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +pub fn reword_safe(
we should cover this with unittests

2020-10-25 14:27 UTC, extrawurst commented on src/components/reword.rs
> +            if let Event::Key(e) = ev {
the current commit msg popup allows opening an external editor (`vi`) to edit the msg, we should have the same option here

2020-10-27 23:47 UTC, extrawurst requested changes

2020-10-27 23:47 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +        Some(top_branch_commit),
let's make this a single `Option<(commit,ref,name)>`

2020-10-27 23:47 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +/// always be wrapped by another function which aborts the rebase if something goes worng
typo: "wrong"

2020-10-27 23:47 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +pub fn reword_safe(
lets call this `reword` and the internal one `reword_internal` or something

2020-10-27 23:47 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +    for b in repo.branches(None)? {
we already do *finding head branch* in `get_branch_name` lets extract an internal `get_head_branch` for this

2020-10-27 23:47 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +    // Repo is not on a branch, possibly detached head
would be nice to early out instead of moving into the long if above

2020-10-27 23:47 UTC, extrawurst commented on src/app.rs
> +    cur_editor_visible: EditorVisible,
I think we should put this into one variable together with `file_to_open`. meaning that we request the external editor to open using `InternalEvent::OpenExternalEditor` and passing the optional path to the file we also pass the editor that requested it so that we know where to return to afterwards.

so that `file_to_open` becomes something like `external_editor: Option<{Path: Option<String>, source: EditorSource}>`

2020-10-27 23:47 UTC, extrawurst commented on src/app.rs
> +    reword_popup: RewordComponent,
let's rather extend the current existing `CommitComponent`

2020-11-05 19:37 UTC, WizardOhio24 commented on asyncgit/src/sync/rebase.rs
> +        Some(top_branch_commit),
Each of these can fail and return None, so this would just add a line where each are checked for if they are `some` and put in that format, `Option<commit, ref, name>`, which means it just moves the checks.  What would adding this achieve/How would this be added?

2020-11-05 19:38 UTC, WizardOhio24 commented on asyncgit/src/sync/rebase.rs
> +pub fn reword_safe(
I think `reword` and `reword_safe` are better names because they better represent what they do, but I'm happy to change it. With `reword_internal` and `reword`, I understand what you are trying to say but I don't think it's that kind of relationship, `reword` does exactly that, but it doesn't do anything else(if it errored the user has to face the consequences), while `reword_safe` does `reword` but catches any errors and fixes the repo for the user.  This is usually what the user wants, but this is not just rewording, this is rewording and fixing if there are errors.  Do you still want this to be changed?

2020-11-05 19:41 UTC, WizardOhio24 commented on asyncgit/src/sync/rebase.rs
> +    // Repo is not on a branch, possibly detached head
What do you mean?

2020-11-05 19:50 UTC, WizardOhio24 commented on src/app.rs
> +    reword_popup: RewordComponent,
How would this work?  This would be like merging two components with separate commands, titles, everything,  and use a lot of if's to check which the user is doing.  Why would this be added to commit?  Plus this is rebasing, not like `commit amend`, so I think these should be kept separate, so as to reflect best the way git works.

2020-11-05 19:53 UTC, WizardOhio24 commented on src/app.rs
> +    cur_editor_visible: EditorVisible,
In this PR?  I can make another PR for that after this one, "Refactor file_to_open".  Should be a simple fix.

2020-11-05 20:07 UTC, WizardOhio24 commented on asyncgit/src/sync/rebase.rs
> +    // Repo is not on a branch, possibly detached head
That's what all the if let Some()...s were for, they would be None if the user was not on a branch, so this does already early out, is that what you're talking about?

2020-11-06 00:02 UTC, extrawurst commented on src/app.rs
> +    cur_editor_visible: EditorVisible,
makes sense in this PR

2020-11-06 00:12 UTC, WizardOhio24 commented on src/app.rs
> +    cur_editor_visible: EditorVisible,
Ok, I'm just trying to keep my PRs smaller and more contained on individual features after the... the branch upstream one(337), and I felt that this is a seperate thing, like a refactor of the external editor, but I can do it in this one, no problem.

2020-11-06 00:23 UTC, extrawurst requested changes

2020-11-06 00:23 UTC, extrawurst commented on asyncgit/src/sync/branch.rs
> +pub fn get_cur_branch(
can be `pub(crate)` since we do not expect the user to use `git2-rs` directly

2020-11-06 00:23 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +/// is implimented in git2rs
typo: `implemented`

2020-11-06 00:23 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +pub fn reword_safe(
my primary concern is to keep a reasonable public API. `reword_safe` makes only sense if you look at `reword` which not even publicly exposed (which I think is the right decision). I am open for better names but my preferences is to have verbose naming for the internal one and clear and short one for the public facing one.

2020-11-06 00:23 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +        Some(top_branch_commit),
a) this is how you can combine `Options:
```
let a  = Some(1);
let b  = Some(2);
let ab = a.zip(b);
```

b) please use the new `bytes2string` helper to make the upper code less verbose for extracting branch name and ref name

2020-11-06 00:23 UTC, extrawurst commented on asyncgit/src/sync/commit.rs
> +pub fn signature_allow_undefined_name(
why do we need to make this public? again this is of no use for the user of this library since we expect them not to directly use `git2-rs`

2020-11-06 00:23 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +    for b in repo.branches(None)? {
can we use the new `get_cur_branch` here?

2020-11-07 00:29 UTC, WizardOhio24 commented on asyncgit/src/sync/rebase.rs
> +        Some(top_branch_commit),
Turns out you don't need options

2020-11-07 00:32 UTC, WizardOhio24 commented on asyncgit/src/sync/rebase.rs
> +    // Repo is not on a branch, possibly detached head
I am assuming the most recent code resolves this? In that if the user is not on a branch, it doesn't start a rebase.

2020-11-16 22:59 UTC, WizardOhio24 commented on asyncgit/src/sync/commit.rs
> +pub fn signature_allow_undefined_name(
This is async git, and there are other pub functions there, e.g `commit`, `amend`, but ok, it can be pub crate.

2020-11-16 23:38 UTC, WizardOhio24 commented on src/app.rs
> +    cur_editor_visible: EditorVisible,
I have made a different PR for it, I'm unsure about how you see this implemented, but I'll try to get the implementation right.

2020-11-16 23:39 UTC, WizardOhio24 commented on src/app.rs
> +    cur_editor_visible: EditorVisible,
Continued in #428

2021-02-02 20:03 UTC, WizardOhio24 commented
With this, should the character count in the reword input box be shown?  e.g, if the user wants to know if the commit message length?

2021-02-02 20:05 UTC, WizardOhio24 commented
It's true for commit message, I'll set the show character count to true.

2021-02-04 13:40 UTC, extrawurst requested changes

2021-02-04 13:40 UTC, extrawurst commented on asyncgit/src/sync/branch.rs
> +pub fn get_cur_branch_ref(repo_path: &str) -> Result<Option<String>> {
please use `get_head_refname` instead

2021-02-04 13:40 UTC, extrawurst commented on src/components/reword.rs
> +        //TODO: use a tmpfile here
lets fix that before we merge, adding a new `TODO` will never be fixed otherwise :)

2021-02-04 13:40 UTC, extrawurst commented on src/strings.rs
> +            "tag commit",
"tag"? looks like a copy/paste mistake

2021-02-04 14:33 UTC, WizardOhio24 commented on src/components/reword.rs
> +        //TODO: use a tmpfile here
I think the fix was in #428, or related to it, I'll move that commit over to here, can't remember exactly what #428 does.

2021-02-06 15:03 UTC, WizardOhio24 commented on src/components/reword.rs
> +        //TODO: use a tmpfile here
I'll fix the one in commit while I'm at it, that's where this was originally from.

2021-04-29 23:05 UTC, WizardOhio24 commented
Updated to master.

2021-05-17 22:26 UTC, extrawurst commented
superseded by #672

2021-05-18 01:20 UTC, WizardOhio24 commented
This has nothing to do with #672?  This is about rewording commits in the log tab, nothing to do with searching.  
Perhaps you meant to close #506?  (Feel free, it has been superceded).

2021-05-18 10:08 UTC, extrawurst commented
was too late, of course I meant to close #506

2021-05-27 20:41 UTC, extrawurst requested changes
I worked through all of this again and it cannot be merged:

<img width="1100" alt="Screenshot 2021-05-27 at 22 19 53" src="https://user-images.githubusercontent.com/776816/119893825-26831580-bf3c-11eb-8b29-50abbd159fce.png">

this happens right when I simply open the commit popup, go to external editor and close it again. this is currently broken.

most of the external editor stuff can be most like reverted anyway if you use the `Mode` in the commit popup. actually the entire reword-popup can now be handled inside `CommitComponent`, this would be much easier I think

2021-05-27 20:41 UTC, extrawurst commented on src/app.rs
> +pub enum EditorSource {
should be put into the `externaleditor.rs`

2021-05-27 20:41 UTC, extrawurst commented on src/app.rs
> +    external_editor: Option<(Option<String>, EditorSource)>,
this should be a struct instead of tuple to help express the intent of this. something like `OpenEditorState`

2021-05-27 20:41 UTC, extrawurst commented on src/app.rs
> +                self.external_editor =
I am not sure why we have to do this now? 
doesn't this trigger `show_editor` now every time we just open the regular commit popup?

2021-05-27 20:41 UTC, extrawurst commented on src/components/externaleditor.rs
> +    let temp_file = NamedTempFile::new()?;
by now we intentionally use a specific filename to edit commit msgs in so that vim knows how to highlight it, we should keep doing this (see `COMMIT_EDITMSG`)

2021-05-27 20:41 UTC, extrawurst commented on src/queue.rs
> +    OpenExternalEditor(Option<String>, EditorSource),
use a struct like mentioned above

2021-05-27 20:41 UTC, extrawurst commented on src/app.rs
> +                _path,
why don't we need those parameters anymore?

2021-05-27 20:41 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +pub fn get_head_refname(repo_path: &str) -> Result<Option<String>> {
`pub(crate)` this seems to only be needed inside `asyncgit`

2021-05-27 20:41 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +            b.get().name_bytes().to_vec(),
we have `bytes2string` for this

2021-05-27 20:41 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +/// is implemented in git2rs
what does that mean? what does it imply?

2021-05-27 20:41 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +        repo.find_commit(commit_oid)?.parent(0)
what if the commit is a merge commit with multiple parents? please add a unittest for that case

2021-05-27 20:41 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +    if let Ok(Some(branch)) = get_cur_branch(&repo) {
lets map this into the `Err` we want and `?` it here to early out if not on a branch, this makes the rest indent one less and easier to read

2021-05-27 20:41 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +        commit(repo_path, "commit1").unwrap();
the new `write_commit_file` makes creating/writing/committing test files more convenient/easier to read now

2021-05-27 20:41 UTC, extrawurst commented on asyncgit/src/sync/rebase.rs
> +    fn test_reword() -> Result<()> {
we currently only test the happy path, what if the rename does not go through and the rebase has to be rolled back. we need a test for that aswell

2021-05-27 20:42 UTC, extrawurst commented
going back to draft in the meantime. change it back to review once you think its ready 👍

2023-02-18 20:27 UTC, extrawurst commented
closing in favour of https://github.com/extrawurst/gitui/pull/1553

2023-02-18 20:27 UTC, closed without merging