feat: support https push
extrawurst/gitui pull request #353
Opened 2020-10-19 14:51 UTC by alocquet

Fix #344

Finally, I use git2 credential help and I retrieve username/password from :
* git credential manager
* url
* git config

I show username textbox only if I can't retrieve it. I clean credentials after push to avoid keeping it in memory.

2020-10-19 21:13 UTC, extrawurst requested changes
Hey @alocquet thanks for working on this❤️! I have made some comments

2020-10-19 21:13 UTC, extrawurst commented on asyncgit/src/sync/cred.rs
> +use git2::{Config, CredentialHelper};
this new module could be covered with tests, right?

2020-10-19 21:13 UTC, extrawurst commented on asyncgit/src/sync/remotes.rs
> +    let mut first_call_to_credentials = true;
is there no overlap of options to authenticate and it makes sense to try another one if a try fails? Either way we should reference the docs for this: https://libgit2.org/docs/guides/authentication/

2020-10-19 21:13 UTC, extrawurst commented on src/components/push.rs
> +                self.cred = extract_username_password("origin")
shouldn't this also take the const?

2020-10-20 05:40 UTC, alocquet commented on src/components/push.rs
> +    sync::cred::need_username_password,
I agree

2020-10-20 05:40 UTC, alocquet commented on asyncgit/src/sync/cred.rs
> +use git2::{Config, CredentialHelper};
I agree

2020-10-20 05:49 UTC, alocquet commented on asyncgit/src/sync/remotes.rs
> +    let mut first_call_to_credentials = true;
In fact, I don't see how I can display the cred inputs when I am in this callback, because this callback is in asyncgit module and moreover, I think it needs to be blocking : we need to wait user inputs.
This is why I have extracted username and password before push call, so as to ask creds before.

2020-10-20 08:31 UTC, extrawurst commented on asyncgit/src/sync/remotes.rs
> +    let mut first_call_to_credentials = true;
I know I was not thinking about showing the popup during the callbacks. I just thought that the system looks like we have multiple ways to feed Cred to the callback, right? and the callback let's us know if the server accepted them by calling the callback again. so I was wondering if there might be a case where we would have to try different ways to feed the creds that we have?

2020-10-20 10:16 UTC, alocquet commented on asyncgit/src/sync/remotes.rs
> +    let mut first_call_to_credentials = true;
Ok, I understand. I think that for https auth (with user/password), there are no other way to feed the creds. The callback can only be called to ask the user to fill other creds.
I have checked Cargo implementation which is used as reference in a stackoverflow thread and they use 2nd call to callback to give more precision about error :
https://github.com/rust-lang/cargo/blob/9fb208dddb12a3081230a5fd8f470e01df8faa25/src/cargo/sources/git/utils.rs#L747

2020-10-20 10:37 UTC, extrawurst commented on asyncgit/src/sync/remotes.rs
> +    let mut first_call_to_credentials = true;
ok so it's fine to only allow one callback, return a potential error to the user and on a new try they could change their credentials before the callback start

2020-10-20 10:38 UTC, extrawurst commented on asyncgit/src/sync/remotes.rs
> +    let mut first_call_to_credentials = true;
then let's just link the docs that I mentioned and the SO post in the code as a reference and keep it this way

2020-10-20 20:30 UTC, extrawurst commented on asyncgit/src/error.rs
> +    NoRemote,
`NoRemote` might be misleading. Maybe `UnknownRemote`?

2020-10-20 20:30 UTC, extrawurst commented on src/components/cred.rs
> +    pub cred: BasicAuthCredential,
let's make this `private` and use a setter

2020-10-20 21:30 UTC, extrawurst approved these changes

2020-10-25 00:02 UTC, extrawurst commented
@alocquet sorry it takes me so long to get this merged. I hope to have time tomorrow to give it a spin and then merge 🙈

2020-10-25 03:42 UTC, alocquet commented
Don't worry :)

2020-10-25 09:50 UTC, merged

2020-10-25 09:51 UTC, extrawurst commented
Awesome! Works for me. Just gave it a spin! Thanks for working on this❤️!
Maybe its a little more ergonomic to not use the huge default TextInputComponent Size but that's a battle for another day. also using `"".to_string()` I suggest using `String::new()` in the future.