feat: password obfuscation
extrawurst/gitui pull request #376
Opened 2020-10-26 17:29 UTC by alocquet

fix #361 
I don't know if it is ok for you but I managed this one with an input type :
* TEXTAREA = previous behavior
* TEXT : input on one line
* PASSWORD : input on one line and obfuscated

2020-10-26 18:01 UTC, extrawurst commented
@alocquet sounds cool but lets call it more specifically
```
pub enum InputType {
     SINGLELINE,
     MULTILINE,
     PASSWORD,
 }
```

2020-10-26 20:50 UTC, extrawurst requested changes

2020-10-26 20:50 UTC, extrawurst commented on src/components/textinput.rs
> +                    ui::rect_min(10, 3, area)
did you test this with terminals smaller 10?

2020-10-26 20:50 UTC, extrawurst commented on src/components/cred.rs
> +use crate::components::textinput::InputType;
can we merge those uses?

2020-10-26 20:50 UTC, extrawurst commented on src/components/textinput.rs
> +    PASSWORD,
lets go for `Singleline`,`Multiline` and `Password`

2020-10-27 10:22 UTC, alocquet commented on src/components/textinput.rs
> +                    ui::rect_min(10, 3, area)
Nope because it was existing code for multiline input; but it fails with a panic. I think this is the same issue as #370.
I can fix it in another PR if you want ?

2020-10-27 10:36 UTC, extrawurst commented on src/components/textinput.rs
> +                    ui::rect_min(10, 3, area)
yeah good point

2020-10-27 10:39 UTC, merged

2020-10-27 10:39 UTC, extrawurst commented
Nice! Thank you!