fix for linux hooks
extrawurst/gitui pull request #386
Opened 2020-10-28 23:47 UTC by pm100

pre-commit now works

also improved the layout of error message dialog to preserve the message formatting

2020-10-29 01:10 UTC, pm100 commented
actually this fix works on windows too, but it requires git 4 windows to be installed (or anything else that puts bash on the devs path)

2020-10-30 01:40 UTC, extrawurst requested changes

2020-10-30 01:40 UTC, extrawurst commented on README.md
> +a
?

2020-10-30 01:40 UTC, extrawurst commented on asyncgit/src/sync/hooks.rs
> -    let mut bash_args = vec![hook_script.to_string()];
why not just prepend the "-c" here?

2020-10-30 01:40 UTC, extrawurst commented on src/components/commit.rs
> +                    "commit-msg hook error:\n{}",
I think this needs to be `pre-commit` right?

2020-10-30 01:48 UTC, pm100 commented on asyncgit/src/sync/hooks.rs
> -    let mut bash_args = vec![hook_script.to_string()];
because its a 2 item vec not one string. I pass a vec of 2 args "-c" and "'script' arg1 arg2 arg3..."

2020-10-30 01:51 UTC, pm100 commented on asyncgit/src/sync/hooks.rs
> -    let mut bash_args = vec![hook_script.to_string()];
the prepend -c is what I first did, didnt work the args didnt get passed to the script right

2020-10-30 02:02 UTC, extrawurst commented on src/components/msg.rs
> +        let max = lens.iter().max().expect("max");
We never make sure that msg is not empty which would panic here, right?

2020-10-30 02:03 UTC, extrawurst commented on asyncgit/src/sync/hooks.rs
> +pub fn hooks_pre_commit(repo_path: &str) -> Result<HookResult> {
Can you add a test for this ?

2020-10-30 02:05 UTC, extrawurst commented on src/components/msg.rs
> +        let mut width = u16::try_from(*max + 2).expect("cant fail");
Better `expect(“why it can’t fail”)`

2020-10-30 03:27 UTC, pm100 commented on src/components/msg.rs
> +        let max = lens.iter().max().expect("max");
no its fine, just displays an empty box. (I tested it)

2020-10-30 03:47 UTC, pm100 commented
FYI - this code works on both linux and windows on my dev system. But I think thats because I have WSL installed. I am not sure what will happen on the github test systems. So I have tests for both windows and non windows. I will check that in and see what happens. I have resolved all yr other issues.

2020-10-31 12:08 UTC, extrawurst commented on asyncgit/src/sync/hooks.rs
> +    fn test_pre_commit_fail_py() {
can you also add a shell based hook test

2020-10-31 12:10 UTC, extrawurst commented on src/components/msg.rs
> +        let mut max = lens.iter().max().expect("max") + 2;
this will still panic if self.msg is empty

2020-10-31 12:10 UTC, extrawurst commented
@pm100 two more things and we can merge this

2020-10-31 16:56 UTC, pm100 commented on src/components/msg.rs
> +        let mut max = lens.iter().max().expect("max") + 2;
no it wont,  I have actually tested it and it works fine.

2020-11-01 00:06 UTC, merged