WIP: Support force push
extrawurst/gitui pull request #421
Opened 2020-11-13 00:03 UTC by WizardOhio24

Closes #274 

This currently force pushes (with SHIFT+P) but does not ask the user to confirm their action, I'll implement that as well.

2020-11-13 00:27 UTC, WizardOhio24 commented
I added the confirm popup but the confirm box seems a bit small, I'll increase it's size.

2020-11-13 00:39 UTC, WizardOhio24 commented
I think this can be merged(pending review), @extrawurst? The only thing is that it does not use the correct upstream branch at the moment, it uses the fact that the upstream must be named the same as the local in currently (in GitUI), so this will have to be changed when a upstream with a different name is supported.

2020-12-08 13:19 UTC, extrawurst commented
@WizardOhio24 why do you close these?

2020-12-08 13:19 UTC, extrawurst commented
did not have time to review them yet. still working myself through the PRs since yesterday

2020-12-19 16:17 UTC, extrawurst requested changes
@WizardOhio24 I think for `force` we should implement the finding of the remote name instead of simply assuming it is the same as the local branch. in case of force this could otherwise lead to bad surprises, don't you think?

2020-12-19 16:17 UTC, extrawurst commented on assets/vim_style_key_config.ron
> +    force_push: ( code: Char('p'), modifiers: ( bits: 2,),),
doesn't this need to be `'P'` and `bits: 1` like with `delete_branch`?

2021-02-02 22:00 UTC, WizardOhio24 commented
This now force pushes to the same place as a normal push would go to, which I think is just the set upstream repo.

2021-02-02 22:02 UTC, WizardOhio24 commented on assets/vim_style_key_config.ron
> +    force_push: ( code: Char('p'), modifiers: ( bits: 2,),),
It works both ways, but I'll change it to 'P' and bits: 1.

2021-02-04 14:02 UTC, extrawurst commented on asyncgit/src/sync/remotes.rs
> +    force: bool,
this should be tested:
a) that a push that would require `force` fails as expected
b) that force push rewrites history in that case correctly

2021-02-05 00:02 UTC, WizardOhio24 commented on asyncgit/src/sync/remotes.rs
> +    force: bool,
Ok, will need to make tests for `branch_set_upstream` first, can't get it working, saying `panicked at 'Failed to setup': Git(Error { code: -3, klass: 4, message: "cannot set upstream for branch \'master\'" })', asyncgit/src/sync/remotes.rs:330:34`.

2021-02-06 00:17 UTC, WizardOhio24 commented on asyncgit/src/sync/remotes.rs
> +    force: bool,
Force push test working, didn't need `branch_set_upstream`.

2021-02-06 00:19 UTC, WizardOhio24 commented on asyncgit/src/sync/remotes.rs
> +    force: bool,
Don't merge yet, I'll do a test for re-writes history as well.

2021-02-06 00:49 UTC, WizardOhio24 commented on asyncgit/src/sync/remotes.rs
> +    force: bool,
Done

2021-02-23 10:02 UTC, merged

2021-02-23 10:02 UTC, extrawurst commented
@WizardOhio24 thanks man!❤️