Add `g` to toggle between staging and workdir (`workarea`)
extrawurst/gitui pull request #595
Opened 2021-03-20 15:02 UTC by terhechte

As discussed in https://github.com/extrawurst/gitui/issues/594 This adds `g` to toggle between staging and workdir. Needed to find a good term, went with `work area` which would be either staging or workdir. Open for suggestions :)

2021-03-20 16:44 UTC, extrawurst requested changes
added a few comments.

2021-03-20 16:44 UTC, extrawurst commented on src/tabs/status.rs
> +        !matches!(self.focus, Focus::Diff)
let's reuse `!is_focus_on_diff()`

2021-03-20 16:44 UTC, extrawurst commented on src/strings.rs
> +    pub fn toggle_workarea(
lets use two explicit methods here, one for `status_focus_workdir` and `status_focus_stage` then we can go back to the short terms `To Stage`/`To Unstated` like it was before (see https://github.com/extrawurst/gitui/pull/575).

2021-03-20 16:44 UTC, extrawurst commented on src/tabs/status.rs
> +                CommandInfo::new(
lets use two different commands depending on where the focus is (see above)

2021-03-20 16:45 UTC, extrawurst commented
how about using `w` in regular key bindings aswell, now that we have not strong reason to use `g` anyway?

2021-03-20 18:22 UTC, terhechte commented
Good Point ☺️

2021-03-21 17:37 UTC, merged

2021-04-07 05:19 UTC, savchenko commented
Would it make sense to allow <kbd>w</kbd> from the Diff view as well?
It currently does nothing and the only way to switch back is via <kbd>&larr;</kbd>.

2021-04-07 08:08 UTC, extrawurst commented
I do not think this would we intuitive. I prefer the current situation where you always go back and forth with `left`/`right` between the file and the matching diff of that file