Add pop stash command on Staches tab
extrawurst/gitui pull request #628
Opened 2021-04-09 22:59 UTC by brunogouveia

As an alternative to asking whether the stash should be removed every time the user applies it, I added the `stash pop` command to the `Stashes` tab.

I personally prefer having two commands: one for quick apply and one for pop.

Let me know what you think.

Closes #574

2021-04-09 23:01 UTC, brunogouveia commented
This is what it looks like
![Uploading Screenshot 2021-04-10 at 00.00.06.png…]()

2021-04-10 08:33 UTC, extrawurst requested changes
Really cool! Just a few smaller comments

2021-04-10 08:33 UTC, extrawurst commented on asyncgit/src/sync/stash.rs
> +pub fn stash_pop(
please add matching unittests for this new method

2021-04-10 08:33 UTC, extrawurst commented on asyncgit/src/sync/stash.rs
> +    allow_conflicts: bool,
lets simplify the signature as long as we do not make use of `allow_conflicts` to be false anyway

2021-04-10 08:33 UTC, extrawurst commented on src/keys.rs
> +			stash_pop: KeyEvent { code: KeyCode::Char('P'), modifiers: KeyModifiers::SHIFT},
I'd argue that pop should be the default: using `enter` as the key and apply should be the new key (maybe even `a`)

2021-04-10 09:14 UTC, brunogouveia commented on src/keys.rs
> +			stash_pop: KeyEvent { code: KeyCode::Char('P'), modifiers: KeyModifiers::SHIFT},
Either way is fine IMHO, but I slightly prefer apply to be the default (since is the action I mostly use); I only use pop or drop when I'm absolutely sure I don't need that stash anymore.

The reason I decided to create a new key is to not implicitly change the current user experience (e.g., I usually don't check the action bar in order to figure out which key combination triggers an action) and have users accidentally dropping stashes because `enter` used to be `git apply`.  We could make the `default` action configurable (and we could extend this concept to any other tab), although I don't think that is currently supported (?).

Let me know if I should make `pop` the default.

2021-04-10 09:19 UTC, brunogouveia commented on asyncgit/src/sync/stash.rs
> +    allow_conflicts: bool,
My reasoning was to follow how we implemented `stash_apply`, which also is only called with `allow_conflicts: false`. Tbh I assumed there was plans to eventually use this flag, but I can remove it for now.

2021-04-10 09:19 UTC, extrawurst commented on src/keys.rs
> +			stash_pop: KeyEvent { code: KeyCode::Char('P'), modifiers: KeyModifiers::SHIFT},
I am not a fan of config files - there is none in gitui (aside keys and theme)

I was thinking about the same and I would agree if the new action was implicit but it is not it introduces a confirmation

2021-04-10 15:46 UTC, brunogouveia commented on src/tabs/stashlist.rs
> +        match sync::stash_pop(CWD, id) {
This pattern seems pretty common: we run a git command synchronously and queue a `InternalEvent` when it succeeds or a `ShowErrorMsg` otherwise. I will take a look in a more DRY approach for the common cases. I don't want to make it part of this PR though.

2021-04-10 17:14 UTC, brunogouveia commented on src/keys.rs
> +			stash_pop: KeyEvent { code: KeyCode::Char('P'), modifiers: KeyModifiers::SHIFT},
Fair enough. I changed `stash pop`  to be the default and changed `stash apply` to key `a`

2021-04-10 17:14 UTC, brunogouveia commented on asyncgit/src/sync/stash.rs
> +pub fn stash_pop(
Done

2021-04-11 11:17 UTC, merged

2021-04-11 11:17 UTC, extrawurst commented
@brunogouveia Really cool, thanks for this!❤️