Add blame view
extrawurst/gitui pull request #634
Opened 2021-04-11 16:25 UTC by cruessler

This closes #484.

This is a rough draft intended to get initial feedback on the direction. To
test, you can press Enter when the selection in a file tree is on a file that
is tracked by git and you will see the blame for that file. I’ll also attach a
screenshot.

Known issues:

- [ ] Highlight and scrolling is not yet implemented.
- [ ] There is duplicated code that should be removed, in particular
  `string_width_align` which can likely moved to a better location somewhere in
  `utils`.
- [ ] The git operations have no async wrapper yet.
- [ ] The way it is made sure that only one of `blame_file_popup` and
  `inspect_commit_popup` is shown can certainly be improved.
- [ ] `BlameFileComponent::get_lines` is rather large, parts of it should
  probably be factored out.
- [ ] `App::process_internal_events` is almost hitting clippy’s limit of 100
  lines per function.
- [ ] There are no tests yet.
- [ ] When you press Enter on a file that is not tracked by git, `gitui` exits
  with an error.

I will address these issues in the coming days.

Let me know what you think!

2021-04-11 16:28 UTC, cruessler commented
![First draft of the blame view](https://user-images.githubusercontent.com/5648141/114312654-a6236500-9af3-11eb-8b0e-dab205ef3da3.png)

2021-04-11 16:52 UTC, extrawurst commented
Really cool for a start! I agree with all your todo boxes.

just a few additional thoughts:
* I would argue the `FileBlame` should contain the lines of the file and the hunks should only reference line indices. this would be more memory efficient and easier to pipe the lines through a highlighter like `syntect` later (https://lib.rs/crates/syntect)
* the indentation seems off (see the `use` lines not lining up)
* `get_lines` always processes all lines not only the ones visible
* I'd like to see a `|`-line separator between the annotation part and the actual content + line numbers
* the title should contain the blamed file and its commit id (we probably later want to be able to blame files at other points in time in the history/revision for example when inspecting an older commit)
* we started using `unicode-truncate` crate now to do the truncation, you can remove a couple of helpers when switching to those

2021-04-14 14:25 UTC, cruessler commented
@extrawurst I’ll be working on this over the next days, and once I’ve addressed all the issues, I’ll update the PR.

2021-04-18 13:28 UTC, cruessler commented
Although I’m not yet done, many of the outstanding issues are now addressed. I was able to use `tui::widgets::Table` which made aligning the different pieces of information quite easy. `Table` can even manage large parts of the scroll state for us. I think I’m coming closer, but there still are a few issues on my list, in addition to those already mentioned in this thread:

- [ ] `FileBlame`, the data structure that holds blame data for a file, stores `BlameHunk` for each line. This is less memory-efficient, but easier to use. I’m of course happy to change that if a different trade-off is desired.
- [ ] `get_rows`, previously `get_lines`, runs on every call to `draw`. If we stored the intermediate result somewhere, this would not be necessary (I ran into lifetime issues when I first tried).
- [ ] the title does not contain the commit id yet.

![gitui-git-blame-second-draft](https://user-images.githubusercontent.com/5648141/115146359-78d83900-a056-11eb-9370-5331bb8bcd06.png)

2021-04-18 14:37 UTC, extrawurst requested changes
awesome work! we are close

I would actually suggest we get a first iteration of this in and move some of the todos into a followup-pr so that more people can start playing around with this.

I'd suggest we split away the async-part for now.
this means we can focus on testing and usability:

* regarding the `FileBlame` structure I'd say lets keep it like this for now and worry about it further if/once we need to.
* lets run `get_rows` on every draw for now and optimise later (after doing an actual profile session on a big ass file blame)
* no panic on untracked files
* add all the commands where you can trigger a `blame` (maybe rather use `[b]` because `[enter]` is used already in a couple of places)
* fix the popup stacking
* add unittests
* some smaller comments in the inline comments

2021-04-18 14:37 UTC, extrawurst commented on src/components/blame_file.rs
> +            Cell::from(format!("{:>4}{}", line_number, VERTICAL_BAR))
how does this work? is it aligning the number to a width of 4 digits? how does this behave in files with 5 digit line numbers or more?

2021-04-18 14:37 UTC, extrawurst commented on src/components/blame_file.rs
> +        let author = format!("{:20}", truncated_author);
in the commit log we do not simply truncate the author, we add `..` - we should make this a reusable function and do the same here

2021-04-18 14:37 UTC, extrawurst commented on src/components/blame_file.rs
> +            ScrollType::End => max_selection,
we should also support pageup/down

2021-04-18 14:37 UTC, extrawurst commented on src/app.rs
> +                self.blame_file_popup.hide();
so far we were able to solve this by stacking popups on top of each other and rely on a well defined order. in this case we might still get by with the same. `blame-popup`>`commit-popup` and if we should add going to a `commit-popup` based on a hunk in the the `blame-popup` we close the blame. what do you think?

long term we might need a breadcrum system so we can implement nice `go-back` functionality but that is a battle for another day

2021-04-18 14:37 UTC, extrawurst commented on asyncgit/src/sync/blame.rs
> +                let start_line = hunk.final_start_line() - 1;
weird that it does not complain, this could technically wrap around..

2021-04-18 14:37 UTC, extrawurst commented on asyncgit/src/sync/blame.rs
> +    // https://github.com/rust-lang/git2-rs/blob/7912c90991444abb00f9d0476939d48bc368516b/examples/blame.rs
what does that mean?

2021-04-18 14:37 UTC, extrawurst commented on asyncgit/src/sync/blame.rs
> +    let object = repo.revparse_single(&spec[..])?;
isn't there `as_slice` for this?

2021-04-18 14:37 UTC, extrawurst commented on asyncgit/src/sync/blame.rs
> +    let repo_path = CWD;
you want this to be a param, to be able to unittest this

2021-04-20 15:00 UTC, cruessler commented on src/components/blame_file.rs
> +            Cell::from(format!("{:>4}{}", line_number, VERTICAL_BAR))
Yes, this is aligning numbers to 4 digits width, padding left with spaces. I changed the line to take the maximum number of lines into account, so 4 is not hard-coded anymore.

2021-04-20 15:01 UTC, cruessler commented on src/components/blame_file.rs
> +        let author = format!("{:20}", truncated_author);
Thanks for the hint. Changed.

2021-04-20 15:01 UTC, cruessler commented on src/components/blame_file.rs
> +            ScrollType::End => max_selection,
Changed.

2021-04-20 15:02 UTC, cruessler commented on src/app.rs
> +                self.blame_file_popup.hide();
Thanks for the info. I was able to delete the extra call and rely on the order `draw` is called in. As far as I can see, there is no need to call `hide` anymore.

2021-04-20 15:03 UTC, cruessler commented on asyncgit/src/sync/blame.rs
> +    // https://github.com/rust-lang/git2-rs/blob/7912c90991444abb00f9d0476939d48bc368516b/examples/blame.rs
The following lines were taken from one of `git2-rs`’s examples and I wanted to attribute the code. Seeing that that was rather confusing than helpful, I removed the comment. :-)

2021-04-20 15:05 UTC, cruessler commented on asyncgit/src/sync/blame.rs
> +    let object = repo.revparse_single(&spec[..])?;
Thanks for the hint! `&spec` also works (the code came from one of `git2-rs`’s examples).

2021-04-20 15:05 UTC, cruessler commented on asyncgit/src/sync/blame.rs
> +    let repo_path = CWD;
Thanks for the hint! I added `repo_path` (and `commit_id`) as parameters to `blame_file`.

2021-04-20 15:09 UTC, cruessler commented
I have updated the code. As far as I can see, there are no major issues left! There was only one issue: `[b]` is already taken in some views (it opens `branches`), so `branches` is currently shadowed if `blame` can be used on an item that is selected. Does that work or do you want to use a different shortcut?

2021-04-21 04:20 UTC, cruessler commented
’blame_file’ currently calls ’get_commit_info’ for every line. This can of course be optimized.

2021-04-21 12:39 UTC, extrawurst commented on src/components/blame_file.rs
> +    (width.saturating_sub(19) / 3).max(3).min(AUTHOR_WIDTH)
there is actually `clamp` for this since 1.50: https://doc.rust-lang.org/core/cmp/trait.Ord.html#method.clamp

2021-04-21 12:40 UTC, extrawurst commented on src/components/blame_file.rs
> +static AUTHOR_WIDTH: usize = 20;
this is rather `AUTHOR_MIN_WIDTH`, right?

2021-04-21 12:43 UTC, extrawurst commented on src/components/blame_file.rs
> +const fn number_of_digits(number: usize) -> usize {
funny how this is not in `std` and not even a crate for it :)

2021-04-21 12:44 UTC, extrawurst commented on src/components/blame_file.rs
> +            // U+2502 is BOX DRAWINGS LIGHT VERTICAL.
TUI has some constants for these things actually

2021-04-21 13:02 UTC, extrawurst approved these changes
just a few remaining comments, but no deal breaker so I will merge this

2021-04-21 13:03 UTC, merged

2021-04-21 13:06 UTC, extrawurst commented
@cruessler really great work! Lets do the rest in smaller followups👍 maybe you can start by writing an issue that collects what should still be done, like *making it async*, optimise the *get_commit_info*..

2021-04-22 06:19 UTC, cruessler commented
@extrawurst I imagine there might be follow-ups that could be a `good first issue`. If you agree, I would open those in separate issues and provide a few instructions on how an implementation might look like. Otherwise, I would be perfectly happy to do the changes myself. :-)

2021-04-22 06:25 UTC, cruessler commented on src/components/blame_file.rs
> +    (width.saturating_sub(19) / 3).max(3).min(AUTHOR_WIDTH)
Thanks for the hint! Changed.

2021-04-22 06:25 UTC, cruessler commented on src/components/blame_file.rs
> +static AUTHOR_WIDTH: usize = 20;
I changed it to `MAX_AUTHOR_WIDTH` and introduced an additional `MIN_AUTHOR_WIDTH`.

2021-04-22 06:26 UTC, cruessler commented on src/components/blame_file.rs
> +const fn number_of_digits(number: usize) -> usize {
I was surprised by that, too. :-)

2021-04-22 06:26 UTC, cruessler commented on src/components/blame_file.rs
> +            // U+2502 is BOX DRAWINGS LIGHT VERTICAL.
Thanks for the hint, changed.

2021-04-23 16:26 UTC, extrawurst commented
@cruessler tbh I would like you to take care of the #656 first (all small stuff) and then the async-part separately (both of which is essential before we can release a version with blaming, so that we keep true to our high standards of usability and performance)

2021-04-24 07:02 UTC, cruessler commented
@extrawurst No worries, I didn’t know you wanted to prioritize a quick release. I’ll work on the remaining issues this weekend (so you know when to expect the first PR).