Fixes #632
extrawurst/gitui pull request #640
Opened 2021-04-13 08:54 UTC by shahsurajk

## Fix: 
* Checks for local branch when checking a remote branch out

**Note**:
I'm a first time contributor to this project. Let me know if i've not done something as per the contribution guidelines

2021-04-13 09:22 UTC, shahsurajk commented
is there a way to check these error locally?

2021-04-13 10:38 UTC, brunogouveia commented
Did you running `cargo clippy`?

2021-04-13 12:52 UTC, extrawurst commented
The CI pipeline is defined in the repo itself. we use GitHub actions. you can run the same as the CI locally: 
```
make check
```

2021-04-13 17:00 UTC, shahsurajk commented
> Did you running `cargo clippy`?

Clippy threw this error: 
```
error reading Clippy's configuration file `/home/dvfd/IdeaProjects/gitui/.clippy.toml`: unknown field `msrv`, expected one of `blacklisted-names`, `cognitive-complexity-threshold`, `cyclomatic-complexity-threshold`, `doc-valid-idents`, `too-many-arguments-threshold`, `type-complexity-threshold`, `single-char-binding-names-threshold`, `too-large-for-stack`, `enum-variant-name-threshold`, `enum-variant-size-threshold`, `verbose-bit-mask-threshold`, `literal-representation-threshold`, `trivial-copy-size-limit`, `too-many-lines-threshold`, `array-size-threshold`, `vec-box-size-threshold`, `max-trait-bounds`, `max-struct-bools`, `max-fn-params-bools`, `warn-on-all-wildcard-imports`, `third-party` at line 1 column 1

```

2021-04-13 17:12 UTC, shahsurajk commented
> > Did you running `cargo clippy`?
> 
> Clippy threw this error:
> 
> ```
> error reading Clippy's configuration file `/home/dvfd/IdeaProjects/gitui/.clippy.toml`: unknown field `msrv`, expected one of `blacklisted-names`, `cognitive-complexity-threshold`, `cyclomatic-complexity-threshold`, `doc-valid-idents`, `too-many-arguments-threshold`, `type-complexity-threshold`, `single-char-binding-names-threshold`, `too-large-for-stack`, `enum-variant-name-threshold`, `enum-variant-size-threshold`, `verbose-bit-mask-threshold`, `literal-representation-threshold`, `trivial-copy-size-limit`, `too-many-lines-threshold`, `array-size-threshold`, `vec-box-size-threshold`, `max-trait-bounds`, `max-struct-bools`, `max-fn-params-bools`, `warn-on-all-wildcard-imports`, `third-party` at line 1 column 1
> ```

Figured out the problem, it was my rust version.

2021-04-13 18:40 UTC, extrawurst commented
Hi @shahsurajk thanks for looking into this but I think we want another solution: 
we want a method that checks if there is a local branch that tracks the remote branch we currently have selected. 
if that is the case we want to switch back to local branch view and select that branch instead of doing a new checkout. (if we find multiple such branches, we pick the first)

2021-04-13 21:28 UTC, shahsurajk commented
Umm, @extrawurst so this change actually does the exact same thing.🤔

If you have a local branch tracked a remote and if you try to checkout the same remote once again, the change pushes you back to the local branch view. It also checks if the local branch selected is actually the one tracked by the remote specified. 

What is the other solution you were proposing? I might've misunderstood it altogether. 

Also, do you mind checking the branch out, cause when I was testing it, it actually worked like what you mentioned. 🤔

If not, I'll happily close this PR. Sorry for the friction.

2021-04-13 21:45 UTC, extrawurst requested changes
I left more inline explanation - feel free to pursue this further if you like

2021-04-13 21:45 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +        repo.find_branch(&name, BranchType::Local)
this only checks if there is a local branch with the same name.
a) if this fails it does not mean there is a local branch with another name that track this remote branch
b) if this finds a branch with the same name it does not necessarily mean that this tracks this remote branch

2021-04-13 21:45 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +/// Modify HEAD to point to a branch then checkout head, does not work if there are uncommitted changes
checking for this inside of `checkout_remote_branch` is too late. we want a separate function that checks if we can find any local branch (we need to iterate all) that is a tracking branch of a specific remote branch

2021-04-20 06:05 UTC, shahsurajk commented
closing in favor or a re-implementation.

2021-04-20 06:05 UTC, closed without merging