[wip] check validity of branch name
extrawurst/gitui pull request #759
Opened 2021-06-01 16:49 UTC by franciscod

(Okay, here we go, rust PR number two :woman_dancing:)

I'm definitely certain that this is ugly code. It works, it's probably correct, but it's not pretty. I don't know what I should do to improve it.

Feedback would be greatly appreciated :)

2021-06-01 16:56 UTC, franciscod commented on asyncgit/Cargo.toml
> +# git2 = { path = "../../git2-rs", features = ["vendored-openssl"]}
didn't mean to change this commented one, will rebase it out later.

2021-06-01 17:03 UTC, franciscod commented
that `clippy` thing sure looks handy. will run it locally and use it to improve this :)

2021-06-01 19:41 UTC, extrawurst commented
We need a git2 release. We can’t depend on a revision

2021-06-01 22:26 UTC, extrawurst requested changes

2021-06-01 22:26 UTC, extrawurst commented on asyncgit/src/sync/branch/mod.rs
> +    match git2::Branch::name_is_valid(name) {
please use `?` operator

2021-06-01 22:26 UTC, extrawurst commented on src/components/create_branch.rs
> +                    let branch_name = self.input.get_text();
on `enter` we do not need to do this since the old behaviour did the same already when we simply try to create the branch

2021-06-01 22:26 UTC, extrawurst commented on src/components/create_branch.rs
> +    // mostly copied from commit.rs, maybe could be refactored?
remove code comments, communication with me can happen on GitHub or discord :)

2021-06-01 22:26 UTC, extrawurst commented on src/components/create_branch.rs
> +        match sync::branch_name_is_valid(branch_name) {
right now we do all those checks on each `draw` of our component. what we want is to only perform those checks when our text changed because the user typed something, the `draw` should then only visualise the result of those checks

2021-06-01 22:26 UTC, extrawurst commented on src/components/create_branch.rs
> +// should this be inside CreateBranchComponent for error handling?
a) yes please put it in the `impl` 
b) I dont know what you mean with the error handling part of the question.
c) please use `?` instead of matching and returning a custom error text

2021-06-02 01:47 UTC, franciscod commented on src/components/create_branch.rs
> +    // mostly copied from commit.rs, maybe could be refactored?
yup! just left those to start the chat, as a reminder to be squashed away :)

2021-06-02 02:03 UTC, franciscod commented on src/components/create_branch.rs
> +        match sync::branch_name_is_valid(branch_name) {
ok! should I add a copy of the last string that was a result of `self.input.get_text()`?

2021-06-02 02:04 UTC, franciscod commented on src/components/create_branch.rs
> +                    let branch_name = self.input.get_text();
ah, that's perfect. was a leftover since my first attempt where I missed the "interactive" part

2021-06-02 02:09 UTC, franciscod reviewed
i don't know how I started this review and I don't know how to cancel it

2021-06-03 17:07 UTC, extrawurst commented on src/components/create_branch.rs
> +        match sync::branch_name_is_valid(branch_name) {
nope we want to save the needed information after the user triggered an input. the draw then only shows this state

2021-06-03 17:08 UTC, extrawurst commented
> i don't know how I started this review and I don't know how to cancel it

what do you mean?

2021-06-03 20:01 UTC, franciscod commented on src/components/create_branch.rs
> +        match sync::branch_name_is_valid(branch_name) {
ok cool!

2021-06-04 21:01 UTC, extrawurst requested changes
aside this small improvement we mostly need to wait for a git2-rs release. you can ask Alex in your PR to cut a release

2021-06-04 21:03 UTC, extrawurst commented on src/components/create_branch.rs
> +                self.validate_input()?;
does this even work? IMO every key consumed by `self.input` will not even go here

2021-06-04 21:05 UTC, extrawurst commented
did you test your latest version of this even?

<img width="1178" alt="Screenshot 2021-06-04 at 23 05 18" src="https://user-images.githubusercontent.com/776816/120862505-5c9e4600-c589-11eb-81da-6a0dbf1cd12d.png">

2021-06-04 21:07 UTC, extrawurst commented on src/components/create_branch.rs
> +        self.invalid_name = sync::branch_name_is_valid(branch_name)?;
this cannot work, this is inverted

2021-06-04 21:07 UTC, extrawurst commented on src/components/create_branch.rs
> +        self.invalid_name = false;
this assignment is useless

2021-06-04 22:53 UTC, franciscod commented on src/components/create_branch.rs
> +        self.already_exists = false;
ah, makes sense! will do. thanks!

2021-06-04 22:55 UTC, franciscod commented
sorry for the rushed commit. I was overconfident that it would work. I'll take my time and test every corner of it before requesting a review again.

2021-06-09 21:54 UTC, extrawurst commented
@franciscod I will mark this as draft in the meantime, please ping me when you want me to check it out again 👍

2021-08-03 21:55 UTC, extrawurst commented
@franciscod do you still plan to finish this?

2021-08-15 12:04 UTC, closed without merging