Add `undo_last_commit` command
extrawurst/gitui pull request #769
Opened 2021-06-04 21:36 UTC by remique

Hey again! I started working on #758 but since it’s not finished yet, I am opening Draft Pull Request. It works, but it’s not finished. Am I going in the right direction with this?
* It does not refresh main tab yet (sometimes). You have to switch between tabs to see the change 
* Should there be a popup or some kind of feedback?
* Should `undo_last_commit()` in `utils.rs` be more general function, for future use?

2021-06-04 22:09 UTC, extrawurst commented on asyncgit/src/sync/utils.rs
> +pub fn undo_last_commit(repo_path: &str) -> Result<()> {
please add a unittest to prove that it does what we want and that it fails as expected for example in an empty repo

2021-06-04 22:12 UTC, extrawurst commented
@remique welcome back!🥳

> It does not refresh main tab yet (sometimes). You have to switch between tabs to see the change

you need to send a explicit update request into the queue (check other such functions)

> Should there be a popup or some kind of feedback?

only for the error case, see `try_or_popup` for examples.

> Should undo_last_commit() in utils.rs be more general function, for future use?

not sure what you mean?

2021-06-06 14:19 UTC, remique commented
Unittests can probably be done better? Also, while working on this issue I have noticed that there are some commands with my keybinding (`u`) already assigned. To avoid potential conflicts, I changed `undo_commit` to `SHIFT-U` both in default and vim-keybindings (feel like it’s a bit more natural since it’s not the most used command in the world). Hopefully I didn’t forget about anything.

> not sure what you mean?

Yeah me neither, nevermind 😄

2021-06-06 15:08 UTC, extrawurst requested changes

2021-06-06 15:08 UTC, extrawurst commented on CHANGELOG.md
> +- undo-last-commit command under `[U]` key [[@remique](https://github.com/remique)] ([#758](https://github.com/extrawurst/gitui/issues/758))
this belongs under `Unreleased`

2021-06-06 15:08 UTC, extrawurst commented on asyncgit/src/sync/utils.rs
> +    fn test_undo_commit_empty_repo() -> Result<()> {
no need for a `Result` since we `unwrap` everywhere (which is fine)

2021-06-06 15:08 UTC, extrawurst commented on asyncgit/src/sync/utils.rs
> +        let status_count = |s: StatusType| -> usize {
check out `get_statuses` we use for unittests already

2021-06-06 15:08 UTC, extrawurst commented on asyncgit/src/sync/utils.rs
> +        let full_path = &root.join(file_path);
check out `write_commit_file` for convenience in unittests

2021-06-06 15:08 UTC, extrawurst commented on asyncgit/src/sync/utils.rs
> +        assert_eq!(status_count(StatusType::Stage), 1);
lets assert that the right file is now in status again

2021-06-06 15:09 UTC, extrawurst commented
good work @remique - almost there 👍

2021-06-07 13:16 UTC, remique commented
Okay, so this definitely feels more natural of a test. Thank you so much for the help and hopefully everything is ready for the merge now.

2021-06-07 14:46 UTC, merged

2021-06-07 14:46 UTC, extrawurst commented
@remique thanks ❤️