added ability to delete remote branch
extrawurst/gitui pull request #838
Opened 2021-08-11 11:43 UTC by zcorniere

This MR aim to fix #622.

Please comment, and I will do my best to fix what's wrong.

2021-08-11 19:01 UTC, extrawurst requested changes
Hi thanks for tackling this. I have just added a few inline comments and I have one request: please add a unitest for the `push` version that deletes an upstream branch

2021-08-11 19:01 UTC, extrawurst commented on src/components/reset.rs
> +                Action::DeleteBranch(branch_ref, _) => (
lets actually make use of the param and say whether we are about to *local* or *remote* branch

2021-08-11 22:00 UTC, extrawurst requested changes
wow that was fast, just a few small improvements to make the test more readable

2021-08-12 07:31 UTC, zcorniere commented on asyncgit/src/sync/remotes/push.rs
> +            Repository::init_bare(tmp_upstream_dir.path())
`get_branches_info` uses `utils::repo` which does not support bare repository. And the upstream need to be bare, because `local push doesn't (yet) support pushing to non-bare repo.`

2021-08-12 07:51 UTC, extrawurst commented on asyncgit/src/sync/remotes/push.rs
> +        let (tmp_upstream_dir, _) = repo_init_bare().unwrap();
This gets rid of the explicit `remote` calls and sets up `repo` and `other_repo` as clones. are you still on this?

2021-08-12 07:53 UTC, zcorniere commented on asyncgit/src/sync/remotes/push.rs
> +        let (tmp_upstream_dir, _) = repo_init_bare().unwrap();
Yes I'm on it

2021-08-12 07:53 UTC, extrawurst commented on asyncgit/src/sync/remotes/push.rs
> +            Repository::init_bare(tmp_upstream_dir.path())
good point. but you can use the upstream repo directly instead of recreating it, see `test_delete_remote_branch` for reference

2021-08-12 08:45 UTC, extrawurst commented
lgtm now! Thanks ❤️

2021-08-12 08:50 UTC, extrawurst commented
I just tested the branch a bit and one thing that is a problem is:

```
Error: git error:cannot locate local branch 'fix-708-expand-recursive'; class=Reference (4); code=NotFound (-3)

Caused by:
    cannot locate local branch 'fix-708-expand-recursive'; class=Reference (4); code=NotFound (-3)
```

it fails if you wanna delete a remote branch you don't have a local tracking branch for

2021-08-12 08:54 UTC, zcorniere commented
Interesting ! I'll look into it !

2021-08-15 10:49 UTC, extrawurst commented
@zcorniere deleting a remote branch you do not have a local tracking branch for, this still crashes gitui.
here is the log:

```
10:46:10 [DEBUG] (7) asyncgit::sync::remotes::callbacks: update tips: 'refs/remotes/origin/fix-708-expand-recursive' [4b06621981b116981098b5cad370ee7c9e513a66] [00000000000000000
00000000000000000000000]
10:46:10 [TRACE] (7) scopetime: [scopetime/src/lib.rs:41] scopetime: 1769 ms [asyncgit::sync::remotes::push::push] @asyncgit/src/sync/remotes/push.rs:102
10:46:11 [ERROR] panic: PanicInfo { payload: Any { .. }, message: Some(cast x: f64 to u8 (nearest): range error for x = NaN), location: Location { file: "/Users/stephan/.cargo/re
gistry/src/github.com-1ecc6299db9ec823/easy-cast-0.4.4/src/lib.rs", line: 670, col: 1 } }
trace:
   ...
  13: asyncgit::progress::ProgressPercent::new
             at asyncgit/src/progress.rs:18:24
  14: asyncgit::remote_progress::RemoteProgress::new
             at asyncgit/src/remote_progress.rs:50:23
  15: <asyncgit::remote_progress::RemoteProgress as core::convert::From<asyncgit::sync::remotes::push::ProgressNotification>>::from
             at asyncgit/src/remote_progress.rs:134:18
  ...
```

2021-08-15 10:50 UTC, extrawurst requested changes
still crashing, see above

2021-08-15 10:55 UTC, zcorniere commented
Sorry, it worked on my end. Thanks for the log, I'm on it !

2021-08-15 14:59 UTC, zcorniere commented
I'm not able to reproduce this behaviour, apologies :(

2021-08-15 15:44 UTC, extrawurst commented
@zcorniere ok I fixed that for you on master: 62ea1de

2021-08-15 15:44 UTC, merged

2021-08-15 15:46 UTC, extrawurst commented
@zcorniere thanks for you time and effort ❤️

2021-08-15 15:46 UTC, extrawurst commented
> I'm not able to reproduce this behaviour, apologies :(

it was a classic *divide by* because apparently libgit sends us a progress update of 0 progress of 0 total :D