Issue/768/support markdown emoji
extrawurst/gitui pull request #866
Opened 2021-08-21 17:04 UTC by andrewpollack

Thank you again for the advice on the previous PR! This is helping me learn better Rust coding practices, and I very much appreciate it :smile: 

This Pull Request fixes/closes #{768}.

It changes the following:
- Adds `gh-emoji` crate to dependencies.
- Updated changelog with png of change in action.
- Added new `fn emojifi_string(s: &str) -> String` to `utils/mod.rs`.
- Utilized above function to emojify messages in `LogEntry`.

I followed the checklist:
- [:heavy_check_mark: ] I added unittests
- [:heavy_check_mark: ] I ran `make check` without errors
- [:heavy_check_mark: ] I tested the overall application
- [:heavy_check_mark: ] I added an appropriate item to the changelog

2021-08-21 18:25 UTC, andrewpollack commented
My local `cargo fmt -- --check` fails on this line here https://github.com/extrawurst/gitui/blob/779a811b58a756f0dfcd8358d9a6025219142f77/asyncgit/src/sync/tags.rs#L45 , but when I make the suggested changes, they fail for the linting that's run in the CI/CD here. Any thoughts on what I should do here?

2021-08-21 22:23 UTC, extrawurst requested changes

2021-08-21 22:23 UTC, extrawurst commented on src/components/utils/mod.rs
> +	let r = gh_emoji::Replacer::new();
Replacer uses a regex internally and creating this over and over again is considered an antipattern. We should use lazy_static to do it just once.

2021-08-21 22:23 UTC, extrawurst commented on src/components/utils/mod.rs
> +	r.replace_all(&*s).to_string()
Too bad we cannot replace in-place here and we create a string copy everytime even if no emoji was found. That’s a deal breaker.
We should take the string in as a mutable reference And check whether the Cow is Cow::Owned (the result from replacer) and only then change the original string

2021-08-22 02:22 UTC, andrewpollack commented on src/components/utils/mod.rs
> +	r.replace_all(&*s).to_string()
Agreed -- happy to find ways to fix the performance. A couple of questions -- 
1. Would this mean that the function would be: `pub fn emojifi_string(s: &mut Cow<&str>) -> String`?
2. Since the `msg` of `LogEntry` is typed String, does this mean I would need to cast it using this `Cow`? I'm a little unfamiliar with `Cow`, but my initial thought is that casting `c.message` in any form would mess up with this check. Is there any example of this pattern of converting `String` into `Cow` without clobbering the typing checks?

2021-08-22 16:33 UTC, andrewpollack commented on src/components/utils/mod.rs
> +	r.replace_all(&*s).to_string()
I gave it a go, and did what I believe should only change the original string should an emoji be present! 
I should note I am quite new to Rust, so thank you for your patience, and I appreciate the guidance in this PR :smile: 

As well, I had to change the original `CommitInfo` header to `mut` to allow the passing of `&mut c.message`!

2021-08-23 09:49 UTC, extrawurst commented on src/components/utils/mod.rs
> +	r.replace_all(&*s).to_string()
you still made a `to_string` even if the replacer still only had a borrow, thats what we do not want. I cleaned that up and I think its good to go now

2021-08-23 09:56 UTC, extrawurst approved these changes

2021-08-23 10:09 UTC, merged

2021-08-23 10:11 UTC, extrawurst commented
@andrewpollack thanks for your contribution. Checkout d72dcddf14f8684b5d686ad74600c24a763eb15d To see what I improved

2021-08-24 02:46 UTC, andrewpollack commented on src/components/utils/mod.rs
> +	r.replace_all(&*s).to_string()
Thank you for this! This is super valuable for me to look at and reference when doing clean implementations in the future :]