Use git_message_prettify
extrawurst/gitui pull request #924
Opened 2021-09-29 18:50 UTC by R0nd

This Pull Request fixes/closes #917.

It changes the following:
Adds message cleanup using built-in git_message_prettify function on commit
Changes custom cleanup for git_message_prettify after using external commit message editor

I followed the checklist:
- [ ] I added unittests
- [x] I ran `make check` without errors
- [x] I tested the overall application
- [x] I added an appropriate item to the changelog

2021-09-29 19:13 UTC, extrawurst requested changes

2021-09-29 19:13 UTC, extrawurst commented on src/components/commit.rs
> +	fn prettify_message(&mut self, msg: String) -> String {
no need for this function

2021-09-29 19:13 UTC, extrawurst commented on src/components/commit.rs
> +		let mut msg = self.prettify_message(msg);
we can use ?-op to propagate a result

2021-09-29 19:36 UTC, R0nd commented on src/components/commit.rs
> +	fn prettify_message(&mut self, msg: String) -> String {
I figured that the potential `Error` result from `message_prettify` needed handling in the context of this class, and since it's used twice might as well make it a function. Do you suggest we should duplicate the error handling for each use case?

2021-09-30 21:20 UTC, merged

2021-09-30 21:20 UTC, extrawurst commented
@R0nd thanks ❤️